/**
 * CS2 weapon paint indices generated from skins.json
 * This enum maps paint names to their corresponding paint index values
 */

export enum WeaponPaint {
    // Default/Vanilla
    VANILLA = 0,

    // AK-47 Skins
    AK_47_RED_LAMINATE = 14, // Red Laminate
    AK_47_CASE_HARDENED = 44, // Case Hardened
    AK_47_SAFARI_MESH = 72, // Safari Mesh
    AK_47_THE_OUTSIDERS = 113, // The Outsiders
    AK_47_JUNGLE_SPRAY = 122, // Jungle Spray
    AK_47_B_THE_MONSTER = 142, // B the Monster
    AK_47_PREDATOR = 170, // Predator
    AK_47_BLACK_LAMINATE = 172, // Black Laminate
    AK_47_FIRE_SERPENT = 180, // Fire Serpent
    AK_47_BLUE_LAMINATE = 226, // Blue Laminate
    AK_47_REDLINE = 282, // Redline
    AK_47_EMERALD_PINSTRIPE = 300, // Emerald Pinstripe
    AK_47_VULCAN = 302, // Vulcan
    AK_47_JAGUAR = 316, // Jaguar
    AK_47_JET_SET = 340, // Jet Set
    AK_47_FIRST_CLASS = 341, // First Class
    AK_47_WASTELAND_REBEL = 380, // Wasteland Rebel
    AK_47_CARTEL = 394, // Cartel
    AK_47_ELITE_BUILD = 422, // Elite Build
    AK_47_HYDROPONIC = 456, // Hydroponic
    AK_47_AQUAMARINE_REVENGE = 474, // Aquamarine Revenge
    AK_47_FRONTSIDE_MISTY = 490, // Frontside Misty
    AK_47_POINT_DISARRAY = 506, // Point Disarray
    AK_47_FUEL_INJECTOR = 524, // Fuel Injector
    AK_47_NEON_REVOLUTION = 600, // Neon Revolution
    AK_47_BLOODSPORT = 639, // Bloodsport
    AK_47_ORBIT_MK01 = 656, // Orbit Mk01
    AK_47_THE_EMPRESS = 675, // The Empress
    AK_47_NEON_RIDER = 707, // Neon Rider
    AK_47_WILD_LOTUS = 724, // Wild Lotus
    AK_47_BAROQUE_PURPLE = 745, // Baroque Purple
    AK_47_SAFETY_NET = 795, // Safety Net
    AK_47_ASIIMOV = 801, // Asiimov
    AK_47_UNCHARTED = 836, // Uncharted
    AK_47_RAT_ROD = 885, // Rat Rod
    AK_47_CROSSFADE = 912, // Crossfade
    AK_47_GOLD_ARABESQUE = 921, // Gold Arabesque
    AK_47_PHANTOM_DISRUPTOR = 941, // Phantom Disruptor
    AK_47_LEGION_OF_ANUBIS = 959, // Legion of Anubis
    AK_47_X_RAY = 1004, // X-Ray
    AK_47_PANTHERA_ONCA = 1018, // Panthera onca
    AK_47_SLATE = 1035, // Slate
    AK_47_GREEN_LAMINATE = 1070, // Green Laminate
    AK_47_LEET_MUSEO = 1087, // Leet Museo
    AK_47_NIGHTWISH = 1141, // Nightwish
    AK_47_ICE_COALED = 1143, // Ice Coaled
    AK_47_INHERITANCE = 1171, // Inheritance
    AK_47_OLIVE_POLYCAM = 1179, // Olive Polycam
    AK_47_SEARING_RAGE = 1207, // Searing Rage
    AK_47_MIDNIGHT_LAMINATE = 1218, // Midnight Laminate
    AK_47_HEAD_SHOT = 1221, // Head Shot
    AK_47_STEEL_DELTA = 1238, // Steel Delta
    AK_47_WINTERGREEN = 1283, // Wintergreen
    AK_47_VARICAMO_GREY = 1288, // VariCamo Grey
    AK_47_NOUVEAU_ROUGE = 1309, // Nouveau Rouge

    // AUG Skins
    AUG_BENGAL_TIGER = 9, // Bengal Tiger
    AUG_COPPERHEAD = 10, // Copperhead
    AUG_HOT_ROD = 33, // Hot Rod
    AUG_CONTRACTOR = 46, // Contractor
    AUG_COLONY = 47, // Colony
    AUG_WINGS = 73, // Wings
    AUG_STORM = 100, // Storm
    AUG_CONDEMNED = 110, // Condemned
    AUG_LUXE_TRIM = 121, // Luxe Trim
    AUG_EYE_OF_ZAPEMS = 134, // Eye of Zapems
    AUG_LIL_PIG = 173, // Lil' Pig
    AUG_ANODIZED_NAVY = 197, // Anodized Navy
    AUG_AMBER_FADE = 246, // Amber Fade
    AUG_CHAMELEON = 280, // Chameleon
    AUG_TORQUE = 305, // Torque
    AUG_RADIATION_HAZARD = 375, // Radiation Hazard
    AUG_DAEDALUS = 444, // Daedalus
    AUG_AKIHABARA_ACCEPT = 455, // Akihabara Accept
    AUG_RICOCHET = 507, // Ricochet
    AUG_FLEET_FLOCK = 541, // Fleet Flock
    AUG_ARISTOCRAT = 583, // Aristocrat
    AUG_SYD_MEAD = 601, // Syd Mead
    AUG_TRIQUA = 674, // Triqua
    AUG_STYMPHALIAN = 690, // Stymphalian
    AUG_AMBER_SLIPSTREAM = 708, // Amber Slipstream
    AUG_MIDNIGHT_LILY = 727, // Midnight Lily
    AUG_NAVY_MURANO = 740, // Navy Murano
    AUG_FLAME_JRMUNGANDR = 758, // Flame Jörmungandr
    AUG_RANDOM_ACCESS = 779, // Random Access
    AUG_SWEEPER = 794, // Sweeper
    AUG_SAND_STORM = 823, // Sand Storm
    AUG_MOMENTUM = 845, // Momentum
    AUG_ARCTIC_WOLF = 886, // Arctic Wolf
    AUG_DEATH_BY_PUPPY = 913, // Death by Puppy
    AUG_SPALTED_WOOD = 927, // Spalted Wood
    AUG_TOM_CAT = 942, // Tom Cat
    AUG_SURVEILLANCE = 995, // Surveillance
    AUG_CARVED_JADE = 1033, // Carved Jade
    AUG_PLAGUE = 1088, // Plague
    AUG_STEEL_SENTINEL = 1198, // Steel Sentinel
    AUG_SNAKE_PIT = 1249, // Snake Pit
    AUG_COMMANDO_COMPANY = 1308, // Commando Company

    // AWP Skins
    AWP_SNAKE_CAMO = 30, // Snake Camo
    AWP_LIGHTNING_STRIKE = 51, // Lightning Strike
    AWP_SAFARI_MESH = 72, // Safari Mesh
    AWP_PINK_DDPAT = 84, // Pink DDPAT
    AWP_CRAKOW = 137, // Crakow!
    AWP_CMYK = 163, // CMYK
    AWP_BOOM = 174, // BOOM
    AWP_CORTICERA = 181, // Corticera
    AWP_GRAPHITE = 212, // Graphite
    AWP_ELECTRIC_HIVE = 227, // Electric Hive
    AWP_PIT_VIPER = 251, // Pit Viper
    AWP_REDLINE = 259, // Redline
    AWP_ASIIMOV = 279, // Asiimov
    AWP_DRAGON_LORE = 344, // Dragon Lore
    AWP_MAN_O_WAR = 395, // Man-o'-war
    AWP_WORM_GOD = 424, // Worm God
    AWP_MEDUSA = 446, // Medusa
    AWP_SUN_IN_LEO = 451, // Sun in Leo
    AWP_HYPER_BEAST = 475, // Hyper Beast
    AWP_ELITE_BUILD = 525, // Elite Build
    AWP_PHOBOS = 584, // Phobos
    AWP_FEVER_DREAM = 640, // Fever Dream
    AWP_ONI_TAIJI = 662, // Oni Taiji
    AWP_MORTIS = 691, // Mortis
    AWP_PAW = 718, // PAW
    AWP_THE_PRINCE = 736, // The Prince
    AWP_GUNGNIR = 756, // Gungnir
    AWP_ACHERON = 788, // Acheron
    AWP_NEO_NOIR = 803, // Neo-Noir
    AWP_DESERT_HYDRA = 819, // Desert Hydra
    AWP_ATHERIS = 838, // Atheris
    AWP_CONTAINMENT_BREACH = 887, // Containment Breach
    AWP_WILDFIRE = 917, // Wildfire
    AWP_CAPILLARY = 943, // Capillary
    AWP_EXOSKELETON = 975, // Exoskeleton
    AWP_FADE = 1026, // Fade
    AWP_SILK_TIGER = 1029, // Silk Tiger
    AWP_POP_AWP = 1058, // POP AWP
    AWP_CHROMATIC_ABERRATION = 1144, // Chromatic Aberration
    AWP_CHROME_CANNON = 1170, // Chrome Cannon
    AWP_PRINTSTREAM = 1206, // Printstream
    AWP_LONGDOG = 1213, // LongDog
    AWP_DUALITY = 1222, // Duality
    AWP_BLACK_NILE = 1239, // Black Nile
    AWP_GREEN_ENERGY = 1280, // Green Energy
    AWP_ARSENIC_SPILL = 1324, // Arsenic Spill

    // Bayonet Skins
    BAYONET_FOREST_DDPAT = 5, // Forest DDPAT
    BAYONET_CRIMSON_WEB = 12, // Crimson Web
    BAYONET_FADE = 38, // Fade
    BAYONET_NIGHT = 40, // Night
    BAYONET_BLUE_STEEL = 42, // Blue Steel
    BAYONET_STAINED = 43, // Stained
    BAYONET_CASE_HARDENED = 44, // Case Hardened
    BAYONET_SLAUGHTER = 59, // Slaughter
    BAYONET_SAFARI_MESH = 72, // Safari Mesh
    BAYONET_BOREAL_FOREST = 77, // Boreal Forest
    BAYONET_ULTRAVIOLET = 98, // Ultraviolet
    BAYONET_URBAN_MASKED = 143, // Urban Masked
    BAYONET_SCORCHED = 175, // Scorched
    BAYONET_TIGER_TOOTH = 409, // Tiger Tooth
    BAYONET_DAMASCUS_STEEL = 410, // Damascus Steel
    BAYONET_MARBLE_FADE = 413, // Marble Fade
    BAYONET_RUST_COAT = 414, // Rust Coat
    BAYONET_DOPPLER = 417, // Doppler
    BAYONET_LORE = 558, // Lore
    BAYONET_BLACK_LAMINATE = 563, // Black Laminate
    BAYONET_GAMMA_DOPPLER = 568, // Gamma Doppler
    BAYONET_AUTOTRONIC = 573, // Autotronic
    BAYONET_BRIGHT_WATER = 578, // Bright Water
    BAYONET_FREEHAND = 580, // Freehand

    // Bloodhound Gloves Skins
    BLOODHOUND_GLOVES_CHARRED = 10006, // Charred
    BLOODHOUND_GLOVES_SNAKEBITE = 10007, // Snakebite
    BLOODHOUND_GLOVES_BRONZED = 10008, // Bronzed
    BLOODHOUND_GLOVES_GUERRILLA = 10039, // Guerrilla

    // Bowie Knife Skins
    BOWIE_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    BOWIE_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    BOWIE_KNIFE_FADE = 38, // Fade
    BOWIE_KNIFE_NIGHT = 40, // Night
    BOWIE_KNIFE_BLUE_STEEL = 42, // Blue Steel
    BOWIE_KNIFE_STAINED = 43, // Stained
    BOWIE_KNIFE_CASE_HARDENED = 44, // Case Hardened
    BOWIE_KNIFE_SLAUGHTER = 59, // Slaughter
    BOWIE_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    BOWIE_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    BOWIE_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    BOWIE_KNIFE_URBAN_MASKED = 143, // Urban Masked
    BOWIE_KNIFE_SCORCHED = 175, // Scorched
    BOWIE_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    BOWIE_KNIFE_DAMASCUS_STEEL = 411, // Damascus Steel
    BOWIE_KNIFE_MARBLE_FADE = 413, // Marble Fade
    BOWIE_KNIFE_RUST_COAT = 414, // Rust Coat
    BOWIE_KNIFE_DOPPLER = 417, // Doppler
    BOWIE_KNIFE_GAMMA_DOPPLER = 568, // Gamma Doppler
    BOWIE_KNIFE_BRIGHT_WATER = 579, // Bright Water
    BOWIE_KNIFE_FREEHAND = 581, // Freehand
    BOWIE_KNIFE_LORE = 1104, // Lore
    BOWIE_KNIFE_BLACK_LAMINATE = 1109, // Black Laminate
    BOWIE_KNIFE_AUTOTRONIC = 1114, // Autotronic

    // Broken Fang Gloves Skins
    BROKEN_FANG_GLOVES_JADE = 10085, // Jade
    BROKEN_FANG_GLOVES_YELLOW_BANDED = 10086, // Yellow-banded
    BROKEN_FANG_GLOVES_NEEDLE_POINT = 10087, // Needle Point
    BROKEN_FANG_GLOVES_UNHINGED = 10088, // Unhinged

    // Butterfly Knife Skins
    BUTTERFLY_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    BUTTERFLY_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    BUTTERFLY_KNIFE_FADE = 38, // Fade
    BUTTERFLY_KNIFE_NIGHT = 40, // Night
    BUTTERFLY_KNIFE_BLUE_STEEL = 42, // Blue Steel
    BUTTERFLY_KNIFE_STAINED = 43, // Stained
    BUTTERFLY_KNIFE_CASE_HARDENED = 44, // Case Hardened
    BUTTERFLY_KNIFE_SLAUGHTER = 59, // Slaughter
    BUTTERFLY_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    BUTTERFLY_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    BUTTERFLY_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    BUTTERFLY_KNIFE_URBAN_MASKED = 143, // Urban Masked
    BUTTERFLY_KNIFE_SCORCHED = 175, // Scorched
    BUTTERFLY_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    BUTTERFLY_KNIFE_DAMASCUS_STEEL = 411, // Damascus Steel
    BUTTERFLY_KNIFE_MARBLE_FADE = 413, // Marble Fade
    BUTTERFLY_KNIFE_RUST_COAT = 414, // Rust Coat
    BUTTERFLY_KNIFE_GAMMA_DOPPLER = 568, // Gamma Doppler
    BUTTERFLY_KNIFE_BRIGHT_WATER = 579, // Bright Water
    BUTTERFLY_KNIFE_FREEHAND = 581, // Freehand
    BUTTERFLY_KNIFE_DOPPLER = 617, // Doppler
    BUTTERFLY_KNIFE_LORE = 1105, // Lore
    BUTTERFLY_KNIFE_BLACK_LAMINATE = 1110, // Black Laminate
    BUTTERFLY_KNIFE_AUTOTRONIC = 1115, // Autotronic

    // CZ75-Auto Skins
    CZ75_AUTO_CRIMSON_WEB = 12, // Crimson Web
    CZ75_AUTO_SILVER = 32, // Silver
    CZ75_AUTO_JUNGLE_DASHED = 147, // Jungle Dashed
    CZ75_AUTO_HEXANE = 218, // Hexane
    CZ75_AUTO_TREAD_PLATE = 268, // Tread Plate
    CZ75_AUTO_THE_FUSCHIA_IS_NOW = 269, // The Fuschia Is Now
    CZ75_AUTO_VICTORIA = 270, // Victoria
    CZ75_AUTO_TUXEDO = 297, // Tuxedo
    CZ75_AUTO_ARMY_SHEEN = 298, // Army Sheen
    CZ75_AUTO_POISON_DART = 315, // Poison Dart
    CZ75_AUTO_NITRO = 322, // Nitro
    CZ75_AUTO_CHALICE = 325, // Chalice
    CZ75_AUTO_INDIGO = 333, // Indigo
    CZ75_AUTO_TWIST = 334, // Twist
    CZ75_AUTO_TIGRIS = 350, // Tigris
    CZ75_AUTO_GREEN_PLAID = 366, // Green Plaid
    CZ75_AUTO_POLE_POSITION = 435, // Pole Position
    CZ75_AUTO_EMERALD = 453, // Emerald
    CZ75_AUTO_YELLOW_JACKET = 476, // Yellow Jacket
    CZ75_AUTO_RED_ASTOR = 543, // Red Astor
    CZ75_AUTO_IMPRINT = 602, // Imprint
    CZ75_AUTO_POLYMER = 622, // Polymer
    CZ75_AUTO_XIANGLIU = 643, // Xiangliu
    CZ75_AUTO_TACTICAT = 687, // Tacticat
    CZ75_AUTO_ECO = 709, // Eco
    CZ75_AUTO_EMERALD_QUARTZ = 859, // Emerald Quartz
    CZ75_AUTO_MIDNIGHT_PALM = 933, // Midnight Palm
    CZ75_AUTO_SLALOM = 937, // Slalom
    CZ75_AUTO_DISTRESSED = 944, // Distressed
    CZ75_AUTO_VENDETTA = 976, // Vendetta
    CZ75_AUTO_CIRCAETUS = 1036, // Circaetus
    CZ75_AUTO_SYNDICATE = 1064, // Syndicate
    CZ75_AUTO_FRAMEWORK = 1076, // Framework
    CZ75_AUTO_COPPER_FIBER = 1195, // Copper Fiber
    CZ75_AUTO_PINK_PEARL = 1329, // Pink Pearl

    // Classic Knife Skins
    CLASSIC_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    CLASSIC_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    CLASSIC_KNIFE_FADE = 38, // Fade
    CLASSIC_KNIFE_BLUE_STEEL = 42, // Blue Steel
    CLASSIC_KNIFE_STAINED = 43, // Stained
    CLASSIC_KNIFE_CASE_HARDENED = 44, // Case Hardened
    CLASSIC_KNIFE_SLAUGHTER = 59, // Slaughter
    CLASSIC_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    CLASSIC_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    CLASSIC_KNIFE_URBAN_MASKED = 143, // Urban Masked
    CLASSIC_KNIFE_SCORCHED = 175, // Scorched
    CLASSIC_KNIFE_NIGHT_STRIPE = 735, // Night Stripe

    // Desert Eagle Skins
    DESERT_EAGLE_URBAN_DDPAT = 17, // Urban DDPAT
    DESERT_EAGLE_BLAZE = 37, // Blaze
    DESERT_EAGLE_NIGHT = 40, // Night
    DESERT_EAGLE_HYPNOTIC = 61, // Hypnotic
    DESERT_EAGLE_MUDDER = 90, // Mudder
    DESERT_EAGLE_CALLIGRAFFITI = 114, // Calligraffiti
    DESERT_EAGLE_TILTED = 138, // Tilted
    DESERT_EAGLE_GOLDEN_KOI = 185, // Golden Koi
    DESERT_EAGLE_COBALT_DISRUPTION = 231, // Cobalt Disruption
    DESERT_EAGLE_CRIMSON_WEB = 232, // Crimson Web
    DESERT_EAGLE_URBAN_RUBBLE = 237, // Urban Rubble
    DESERT_EAGLE_HEIRLOOM = 273, // Heirloom
    DESERT_EAGLE_METEORITE = 296, // Meteorite
    DESERT_EAGLE_HAND_CANNON = 328, // Hand Cannon
    DESERT_EAGLE_PILOT = 347, // Pilot
    DESERT_EAGLE_CONSPIRACY = 351, // Conspiracy
    DESERT_EAGLE_NAGA = 397, // Naga
    DESERT_EAGLE_BRONZE_DECO = 425, // Bronze Deco
    DESERT_EAGLE_MIDNIGHT_STORM = 468, // Midnight Storm
    DESERT_EAGLE_SUNSET_STORM = 469, // Sunset Storm 壱
    DESERT_EAGLE_CORINTHIAN = 509, // Corinthian
    DESERT_EAGLE_KUMICHO_DRAGON = 527, // Kumicho Dragon
    DESERT_EAGLE_DIRECTIVE = 603, // Directive
    DESERT_EAGLE_OXIDE_BLAZE = 645, // Oxide Blaze
    DESERT_EAGLE_CODE_RED = 711, // Code Red
    DESERT_EAGLE_EMERALD_JRMUNGANDR = 757, // Emerald Jörmungandr
    DESERT_EAGLE_FENNEC_FOX = 764, // Fennec Fox
    DESERT_EAGLE_MECHA_INDUSTRIES = 805, // Mecha Industries
    DESERT_EAGLE_LIGHT_RAIL = 841, // Light Rail
    DESERT_EAGLE_STARCADE = 938, // Starcade
    DESERT_EAGLE_BLUE_PLY = 945, // Blue Ply
    DESERT_EAGLE_PRINTSTREAM = 962, // Printstream
    DESERT_EAGLE_THE_BRONZE = 992, // The Bronze
    DESERT_EAGLE_NIGHT_HEIST = 1006, // Night Heist
    DESERT_EAGLE_TRIGGER_DISCIPLINE = 1050, // Trigger Discipline
    DESERT_EAGLE_HEAT_TREATED = 1054, // Heat Treated
    DESERT_EAGLE_SPUTNIK = 1056, // Sputnik
    DESERT_EAGLE_OCEAN_DRIVE = 1090, // Ocean Drive
    DESERT_EAGLE_SERPENT_STRIKE = 1189, // Serpent Strike
    DESERT_EAGLE_MINT_FAN = 1257, // Mint Fan
    DESERT_EAGLE_MULBERRY = 1318, // Mulberry

    // Driver Gloves Skins
    DRIVER_GLOVES_LUNAR_WEAVE = 10013, // Lunar Weave
    DRIVER_GLOVES_CONVOY = 10015, // Convoy
    DRIVER_GLOVES_CRIMSON_WEAVE = 10016, // Crimson Weave
    DRIVER_GLOVES_DIAMONDBACK = 10040, // Diamondback
    DRIVER_GLOVES_KING_SNAKE = 10041, // King Snake
    DRIVER_GLOVES_IMPERIAL_PLAID = 10042, // Imperial Plaid
    DRIVER_GLOVES_OVERTAKE = 10043, // Overtake
    DRIVER_GLOVES_RACING_GREEN = 10044, // Racing Green
    DRIVER_GLOVES_REZAN_THE_RED = 10069, // Rezan the Red
    DRIVER_GLOVES_SNOW_LEOPARD = 10070, // Snow Leopard
    DRIVER_GLOVES_QUEEN_JAGUAR = 10071, // Queen Jaguar
    DRIVER_GLOVES_BLACK_TIE = 10072, // Black Tie

    // Dual Berettas Skins
    DUAL_BERETTAS_ANODIZED_NAVY = 28, // Anodized Navy
    DUAL_BERETTAS_STAINED = 43, // Stained
    DUAL_BERETTAS_CONTRACTOR = 46, // Contractor
    DUAL_BERETTAS_COLONY = 47, // Colony
    DUAL_BERETTAS_HYDRO_STRIKE = 112, // Hydro Strike
    DUAL_BERETTAS_SWEET_LITTLE_ANGELS = 139, // Sweet Little Angels
    DUAL_BERETTAS_DEMOLITION = 153, // Demolition
    DUAL_BERETTAS_BLACK_LIMBA = 190, // Black Limba
    DUAL_BERETTAS_HEMOGLOBIN = 220, // Hemoglobin
    DUAL_BERETTAS_COBALT_QUARTZ = 249, // Cobalt Quartz
    DUAL_BERETTAS_MARINA = 261, // Marina
    DUAL_BERETTAS_PANTHER = 276, // Panther
    DUAL_BERETTAS_RETRIBUTION = 307, // Retribution
    DUAL_BERETTAS_BRIAR = 330, // Briar
    DUAL_BERETTAS_URBAN_SHOCK = 396, // Urban Shock
    DUAL_BERETTAS_DUELIST = 447, // Duelist
    DUAL_BERETTAS_MOON_IN_LIBRA = 450, // Moon in Libra
    DUAL_BERETTAS_EMERALD = 453, // Emerald
    DUAL_BERETTAS_DUALING_DRAGONS = 491, // Dualing Dragons
    DUAL_BERETTAS_CARTEL = 528, // Cartel
    DUAL_BERETTAS_VENTILATORS = 544, // Ventilators
    DUAL_BERETTAS_ROYAL_CONSORTS = 625, // Royal Consorts
    DUAL_BERETTAS_COBRA_STRIKE = 658, // Cobra Strike
    DUAL_BERETTAS_SHRED = 710, // Shred
    DUAL_BERETTAS_TWIN_TURBO = 747, // Twin Turbo
    DUAL_BERETTAS_DRIFT_WOOD = 824, // Drift Wood
    DUAL_BERETTAS_PYRE = 860, // Pyre
    DUAL_BERETTAS_BALANCE = 895, // Balance
    DUAL_BERETTAS_ELITE_16 = 903, // Elite 1.6
    DUAL_BERETTAS_DEZASTRE = 978, // Dezastre
    DUAL_BERETTAS_SWITCH_BOARD = 998, // Switch Board
    DUAL_BERETTAS_HEIST = 1005, // Heist
    DUAL_BERETTAS_OIL_CHANGE = 1086, // Oil Change
    DUAL_BERETTAS_TREAD = 1091, // Tread
    DUAL_BERETTAS_MELONDRAMA = 1126, // Melondrama
    DUAL_BERETTAS_FLORA_CARNIVORA = 1156, // Flora Carnivora
    DUAL_BERETTAS_HIDEOUT = 1169, // Hideout
    DUAL_BERETTAS_ROSE_NACRE = 1263, // Rose Nacre
    DUAL_BERETTAS_POLISHED_MALACHITE = 1290, // Polished Malachite
    DUAL_BERETTAS_BORDEUX = 1335, // BorDeux

    // FAMAS Skins
    FAMAS_CONTRAST_SPRAY = 22, // Contrast Spray
    FAMAS_COLONY = 47, // Colony
    FAMAS_DARK_WATER = 60, // Dark Water
    FAMAS_CYANOSPATTER = 92, // Cyanospatter
    FAMAS_AFTERIMAGE = 154, // Afterimage
    FAMAS_DOOMKITTY = 178, // Doomkitty
    FAMAS_SPITFIRE = 194, // Spitfire
    FAMAS_HEXANE = 218, // Hexane
    FAMAS_CALICAMO = 240, // CaliCamo
    FAMAS_TEARDOWN = 244, // Teardown
    FAMAS_PULSE = 260, // Pulse
    FAMAS_SERGEANT = 288, // Sergeant
    FAMAS_STYX = 371, // Styx
    FAMAS_DJINN = 429, // Djinn
    FAMAS_HALF_SLEEVE = 461, // Half Sleeve
    FAMAS_NEURAL_NET = 477, // Neural Net
    FAMAS_SURVIVOR_Z = 492, // Survivor Z
    FAMAS_VALENCE = 529, // Valence
    FAMAS_ROLL_CAGE = 604, // Roll Cage
    FAMAS_MECHA_INDUSTRIES = 626, // Mecha Industries
    FAMAS_MACABRE = 659, // Macabre
    FAMAS_EYE_OF_ATHENA = 723, // Eye of Athena
    FAMAS_CRYPSIS = 835, // Crypsis
    FAMAS_NIGHT_BORRE = 863, // Night Borre
    FAMAS_SUNDOWN = 869, // Sundown
    FAMAS_HALFTONE_WASH = 882, // Halftone Wash
    FAMAS_DECOMMISSIONED = 904, // Decommissioned
    FAMAS_COMMEMORATION = 919, // Commemoration
    FAMAS_PRIME_CONSPIRACY = 999, // Prime Conspiracy
    FAMAS_MELTDOWN = 1053, // Meltdown
    FAMAS_FAULTY_WIRING = 1066, // Faulty Wiring
    FAMAS_ZX_SPECTRON = 1092, // ZX Spectron
    FAMAS_RAPID_EYE_MOVEMENT = 1127, // Rapid Eye Movement
    FAMAS_MEOW_36 = 1146, // Meow 36
    FAMAS_BAD_TRIP = 1184, // Bad Trip
    FAMAS_2A2F = 1202, // 2A2F
    FAMAS_YETI_CAMO = 1219, // Yeti Camo
    FAMAS_WATERS_OF_NEPHTHYS = 1241, // Waters of Nephthys
    FAMAS_PALM = 1302, // Palm
    FAMAS_GREY_GHOST = 1321, // Grey Ghost

    // Falchion Knife Skins
    FALCHION_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    FALCHION_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    FALCHION_KNIFE_FADE = 38, // Fade
    FALCHION_KNIFE_NIGHT = 40, // Night
    FALCHION_KNIFE_BLUE_STEEL = 42, // Blue Steel
    FALCHION_KNIFE_STAINED = 43, // Stained
    FALCHION_KNIFE_CASE_HARDENED = 44, // Case Hardened
    FALCHION_KNIFE_SLAUGHTER = 59, // Slaughter
    FALCHION_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    FALCHION_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    FALCHION_KNIFE_URBAN_MASKED = 143, // Urban Masked
    FALCHION_KNIFE_SCORCHED = 175, // Scorched
    FALCHION_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    FALCHION_KNIFE_DAMASCUS_STEEL = 411, // Damascus Steel
    FALCHION_KNIFE_MARBLE_FADE = 413, // Marble Fade
    FALCHION_KNIFE_RUST_COAT = 414, // Rust Coat
    FALCHION_KNIFE_DOPPLER = 417, // Doppler
    FALCHION_KNIFE_GAMMA_DOPPLER = 568, // Gamma Doppler
    FALCHION_KNIFE_BRIGHT_WATER = 579, // Bright Water
    FALCHION_KNIFE_FREEHAND = 581, // Freehand
    FALCHION_KNIFE_ULTRAVIOLET = 621, // Ultraviolet
    FALCHION_KNIFE_LORE = 1106, // Lore
    FALCHION_KNIFE_BLACK_LAMINATE = 1111, // Black Laminate
    FALCHION_KNIFE_AUTOTRONIC = 1116, // Autotronic

    // Five-SeveN Skins
    FIVE_SEVEN_CANDY_APPLE = 3, // Candy Apple
    FIVE_SEVEN_CASE_HARDENED = 44, // Case Hardened
    FIVE_SEVEN_CONTRACTOR = 46, // Contractor
    FIVE_SEVEN_FOREST_NIGHT = 78, // Forest Night
    FIVE_SEVEN_ORANGE_PEEL = 141, // Orange Peel
    FIVE_SEVEN_JUNGLE = 151, // Jungle
    FIVE_SEVEN_ANODIZED_GUNMETAL = 210, // Anodized Gunmetal
    FIVE_SEVEN_NIGHTSHADE = 223, // Nightshade
    FIVE_SEVEN_SILVER_QUARTZ = 252, // Silver Quartz
    FIVE_SEVEN_NITRO = 254, // Nitro
    FIVE_SEVEN_KAMI = 265, // Kami
    FIVE_SEVEN_COPPER_GALAXY = 274, // Copper Galaxy
    FIVE_SEVEN_FOWL_PLAY = 352, // Fowl Play
    FIVE_SEVEN_HOT_SHOT = 377, // Hot Shot
    FIVE_SEVEN_URBAN_HAZARD = 387, // Urban Hazard
    FIVE_SEVEN_MONKEY_BUSINESS = 427, // Monkey Business
    FIVE_SEVEN_NEON_KIMONO = 464, // Neon Kimono
    FIVE_SEVEN_RETROBUTION = 510, // Retrobution
    FIVE_SEVEN_TRIUMVIRATE = 530, // Triumvirate
    FIVE_SEVEN_VIOLENT_DAIMYO = 585, // Violent Daimyo
    FIVE_SEVEN_SCUMBRIA = 605, // Scumbria
    FIVE_SEVEN_CAPILLARY = 646, // Capillary
    FIVE_SEVEN_HYPER_BEAST = 660, // Hyper Beast
    FIVE_SEVEN_FLAME_TEST = 693, // Flame Test
    FIVE_SEVEN_CRIMSON_BLOSSOM = 729, // Crimson Blossom
    FIVE_SEVEN_COOLANT = 784, // Coolant
    FIVE_SEVEN_HEAT_TREATED = 831, // Heat Treated
    FIVE_SEVEN_ANGRY_MOB = 837, // Angry Mob
    FIVE_SEVEN_BUDDY = 906, // Buddy
    FIVE_SEVEN_WITHERED_VINE = 932, // Withered Vine
    FIVE_SEVEN_FAIRY_TALE = 979, // Fairy Tale
    FIVE_SEVEN_BERRIES_AND_CHERRIES = 1002, // Berries And Cherries
    FIVE_SEVEN_MIDNIGHT_PAINTOVER = 1062, // Midnight Paintover
    FIVE_SEVEN_FALL_HAZARD = 1082, // Fall Hazard
    FIVE_SEVEN_BOOST_PROTOCOL = 1093, // Boost Protocol
    FIVE_SEVEN_SCRAWL = 1128, // Scrawl
    FIVE_SEVEN_HYBRID = 1168, // Hybrid
    FIVE_SEVEN_SKY_BLUE = 1262, // Sky Blue
    FIVE_SEVEN_AUTUMN_THICKET = 1336, // Autumn Thicket

    // Flip Knife Skins
    FLIP_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    FLIP_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    FLIP_KNIFE_FADE = 38, // Fade
    FLIP_KNIFE_NIGHT = 40, // Night
    FLIP_KNIFE_BLUE_STEEL = 42, // Blue Steel
    FLIP_KNIFE_STAINED = 43, // Stained
    FLIP_KNIFE_CASE_HARDENED = 44, // Case Hardened
    FLIP_KNIFE_SLAUGHTER = 59, // Slaughter
    FLIP_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    FLIP_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    FLIP_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    FLIP_KNIFE_URBAN_MASKED = 143, // Urban Masked
    FLIP_KNIFE_SCORCHED = 175, // Scorched
    FLIP_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    FLIP_KNIFE_DAMASCUS_STEEL = 410, // Damascus Steel
    FLIP_KNIFE_MARBLE_FADE = 413, // Marble Fade
    FLIP_KNIFE_RUST_COAT = 414, // Rust Coat
    FLIP_KNIFE_DOPPLER = 417, // Doppler
    FLIP_KNIFE_LORE = 559, // Lore
    FLIP_KNIFE_BLACK_LAMINATE = 564, // Black Laminate
    FLIP_KNIFE_GAMMA_DOPPLER = 568, // Gamma Doppler
    FLIP_KNIFE_AUTOTRONIC = 574, // Autotronic
    FLIP_KNIFE_BRIGHT_WATER = 578, // Bright Water
    FLIP_KNIFE_FREEHAND = 580, // Freehand

    // G3SG1 Skins
    G3SG1_ARCTIC_CAMO = 6, // Arctic Camo
    G3SG1_DESERT_STORM = 8, // Desert Storm
    G3SG1_CONTRACTOR = 46, // Contractor
    G3SG1_SAFARI_MESH = 72, // Safari Mesh
    G3SG1_POLAR_CAMO = 74, // Polar Camo
    G3SG1_JUNGLE_DASHED = 147, // Jungle Dashed
    G3SG1_DEMETER = 195, // Demeter
    G3SG1_AZURE_ZEBRA = 229, // Azure Zebra
    G3SG1_VARICAMO = 235, // VariCamo
    G3SG1_GREEN_APPLE = 294, // Green Apple
    G3SG1_MURKY = 382, // Murky
    G3SG1_CHRONOS = 438, // Chronos
    G3SG1_ORANGE_KIMONO = 465, // Orange Kimono
    G3SG1_FLUX = 493, // Flux
    G3SG1_THE_EXECUTIONER = 511, // The Executioner
    G3SG1_ORANGE_CRASH = 545, // Orange Crash
    G3SG1_VENTILATOR = 606, // Ventilator
    G3SG1_STINGER = 628, // Stinger
    G3SG1_HUNTER = 677, // Hunter
    G3SG1_HIGH_SEAS = 712, // High Seas
    G3SG1_VIOLET_MURANO = 739, // Violet Murano
    G3SG1_SCAVENGER = 806, // Scavenger
    G3SG1_BLACK_SAND = 891, // Black Sand
    G3SG1_NEW_ROOTS = 930, // New Roots
    G3SG1_DIGITAL_MESH = 980, // Digital Mesh
    G3SG1_ANCIENT_RITUAL = 1034, // Ancient Ritual
    G3SG1_KEEPING_TABS = 1095, // Keeping Tabs
    G3SG1_DREAM_GLADE = 1129, // Dream Glade
    G3SG1_GREEN_CELL = 1305, // Green Cell
    G3SG1_RED_JASPER = 1328, // Red Jasper

    // Galil AR Skins
    GALIL_AR_WINTER_FOREST = 76, // Winter Forest
    GALIL_AR_ORANGE_DDPAT = 83, // Orange DDPAT
    GALIL_AR_TORNADO = 101, // Tornado
    GALIL_AR_SAGE_SPRAY = 119, // Sage Spray
    GALIL_AR_SHATTERED = 192, // Shattered
    GALIL_AR_BLUE_TITANIUM = 216, // Blue Titanium
    GALIL_AR_VARICAMO = 235, // VariCamo
    GALIL_AR_URBAN_RUBBLE = 237, // Urban Rubble
    GALIL_AR_METALLIC_SQUEEZER = 239, // Metallic Squeezer
    GALIL_AR_HUNTING_BLIND = 241, // Hunting Blind
    GALIL_AR_AMBER_FADE = 246, // Amber Fade
    GALIL_AR_SANDSTORM = 264, // Sandstorm
    GALIL_AR_GREEN_APPLE = 294, // Green Apple
    GALIL_AR_TUXEDO = 297, // Tuxedo
    GALIL_AR_KAMI = 308, // Kami
    GALIL_AR_CERBERUS = 379, // Cerberus
    GALIL_AR_CHATTERBOX = 398, // Chatterbox
    GALIL_AR_ECO = 428, // Eco
    GALIL_AR_AQUA_TERRACE = 460, // Aqua Terrace
    GALIL_AR_ROCKET_POP = 478, // Rocket Pop
    GALIL_AR_STONE_COLD = 494, // Stone Cold
    GALIL_AR_FIREFIGHT = 546, // Firefight
    GALIL_AR_BLACK_SAND = 629, // Black Sand
    GALIL_AR_CRIMSON_TSUNAMI = 647, // Crimson Tsunami
    GALIL_AR_SUGAR_RUSH = 661, // Sugar Rush
    GALIL_AR_COLD_FUSION = 790, // Cold Fusion
    GALIL_AR_SIGNAL = 807, // Signal
    GALIL_AR_AKOBEN = 842, // Akoben
    GALIL_AR_NV = 939, // NV
    GALIL_AR_CONNEXION = 972, // Connexion
    GALIL_AR_VANDAL = 981, // Vandal
    GALIL_AR_PHOENIX_BLACKLIGHT = 1013, // Phoenix Blacklight
    GALIL_AR_DUSK_RUINS = 1032, // Dusk Ruins
    GALIL_AR_CHROMATIC_ABERRATION = 1038, // Chromatic Aberration
    GALIL_AR_CAUTION = 1071, // CAUTION!
    GALIL_AR_DESTROYER = 1147, // Destroyer
    GALIL_AR_RAINBOW_SPOON = 1178, // Rainbow Spoon
    GALIL_AR_CONTROL = 1185, // Control
    GALIL_AR_ROBINS_EGG = 1264, // Robin's Egg
    GALIL_AR_GREY_SMOKE = 1275, // Grey Smoke
    GALIL_AR_ACID_DART = 1296, // Acid Dart
    GALIL_AR_O_RANGER = 1314, // O-Ranger

    // Glock-18 Skins
    GLOCK_18_GROUNDWATER = 2, // Groundwater
    GLOCK_18_CANDY_APPLE = 3, // Candy Apple
    GLOCK_18_FADE = 38, // Fade
    GLOCK_18_NIGHT = 40, // Night
    GLOCK_18_DRAGON_TATTOO = 48, // Dragon Tattoo
    GLOCK_18_PINK_DDPAT = 84, // Pink DDPAT
    GLOCK_18_GOLD_TOOF = 129, // Gold Toof
    GLOCK_18_TEAL_GRAF = 152, // Teal Graf
    GLOCK_18_BRASS = 159, // Brass
    GLOCK_18_SAND_DUNE = 208, // Sand Dune
    GLOCK_18_STEEL_DISRUPTION = 230, // Steel Disruption
    GLOCK_18_BLUE_FISSURE = 278, // Blue Fissure
    GLOCK_18_DEATH_RATTLE = 293, // Death Rattle
    GLOCK_18_WATER_ELEMENTAL = 353, // Water Elemental
    GLOCK_18_REACTOR = 367, // Reactor
    GLOCK_18_GRINDER = 381, // Grinder
    GLOCK_18_CATACOMBS = 399, // Catacombs
    GLOCK_18_TWILIGHT_GALAXY = 437, // Twilight Galaxy
    GLOCK_18_BUNSEN_BURNER = 479, // Bunsen Burner
    GLOCK_18_WRAITHS = 495, // Wraiths
    GLOCK_18_ROYAL_LEGION = 532, // Royal Legion
    GLOCK_18_WASTELAND_REBEL = 586, // Wasteland Rebel
    GLOCK_18_WEASEL = 607, // Weasel
    GLOCK_18_IRONWORK = 623, // Ironwork
    GLOCK_18_OFF_WORLD = 680, // Off World
    GLOCK_18_MOONRISE = 694, // Moonrise
    GLOCK_18_WARHAWK = 713, // Warhawk
    GLOCK_18_SYNTH_LEAF = 732, // Synth Leaf
    GLOCK_18_NUCLEAR_GARDEN = 789, // Nuclear Garden
    GLOCK_18_HIGH_BEAM = 799, // High Beam
    GLOCK_18_OXIDE_BLAZE = 808, // Oxide Blaze
    GLOCK_18_AXIA = 832, // AXIA
    GLOCK_18_SACRIFICE = 918, // Sacrifice
    GLOCK_18_BULLET_QUEEN = 957, // Bullet Queen
    GLOCK_18_VOGUE = 963, // Vogue
    GLOCK_18_NEO_NOIR = 988, // Neo-Noir
    GLOCK_18_FRANKLIN = 1016, // Franklin
    GLOCK_18_CLEAR_POLYMER = 1039, // Clear Polymer
    GLOCK_18_RED_TIRE = 1079, // Red Tire
    GLOCK_18_SNACK_ATTACK = 1100, // Snack Attack
    GLOCK_18_GAMMA_DOPPLER = 1119, // Gamma Doppler
    GLOCK_18_WINTERIZED = 1158, // Winterized
    GLOCK_18_BLOCK_18 = 1167, // Block-18
    GLOCK_18_GREEN_LINE = 1200, // Green Line
    GLOCK_18_SHINOBU = 1208, // Shinobu
    GLOCK_18_UMBRAL_RABBIT = 1227, // Umbral Rabbit
    GLOCK_18_RAMESES_REACH = 1240, // Ramese's Reach
    GLOCK_18_OCEAN_TOPO = 1265, // Ocean Topo
    GLOCK_18_GLOCKINGBIRD = 1282, // Glockingbird
    GLOCK_18_CORAL_BLOOM = 1312, // Coral Bloom

    // Gut Knife Skins
    GUT_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    GUT_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    GUT_KNIFE_FADE = 38, // Fade
    GUT_KNIFE_NIGHT = 40, // Night
    GUT_KNIFE_BLUE_STEEL = 42, // Blue Steel
    GUT_KNIFE_STAINED = 43, // Stained
    GUT_KNIFE_CASE_HARDENED = 44, // Case Hardened
    GUT_KNIFE_SLAUGHTER = 59, // Slaughter
    GUT_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    GUT_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    GUT_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    GUT_KNIFE_URBAN_MASKED = 143, // Urban Masked
    GUT_KNIFE_SCORCHED = 175, // Scorched
    GUT_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    GUT_KNIFE_DAMASCUS_STEEL = 410, // Damascus Steel
    GUT_KNIFE_MARBLE_FADE = 413, // Marble Fade
    GUT_KNIFE_RUST_COAT = 414, // Rust Coat
    GUT_KNIFE_DOPPLER = 417, // Doppler
    GUT_KNIFE_LORE = 560, // Lore
    GUT_KNIFE_BLACK_LAMINATE = 565, // Black Laminate
    GUT_KNIFE_GAMMA_DOPPLER = 568, // Gamma Doppler
    GUT_KNIFE_AUTOTRONIC = 575, // Autotronic
    GUT_KNIFE_BRIGHT_WATER = 578, // Bright Water
    GUT_KNIFE_FREEHAND = 580, // Freehand

    // Hand Wraps Skins
    HAND_WRAPS_LEATHER = 10009, // Leather
    HAND_WRAPS_SPRUCE_DDPAT = 10010, // Spruce DDPAT
    HAND_WRAPS_SLAUGHTER = 10021, // Slaughter
    HAND_WRAPS_BADLANDS = 10036, // Badlands
    HAND_WRAPS_COBALT_SKULLS = 10053, // Cobalt Skulls
    HAND_WRAPS_OVERPRINT = 10054, // Overprint
    HAND_WRAPS_DUCT_TAPE = 10055, // Duct Tape
    HAND_WRAPS_ARBOREAL = 10056, // Arboreal
    HAND_WRAPS_DESERT_SHAMAGH = 10081, // Desert Shamagh
    HAND_WRAPS_GIRAFFE = 10082, // Giraffe
    HAND_WRAPS_CONSTRICTOR = 10083, // Constrictor
    HAND_WRAPS_CAUTION = 10084, // CAUTION!

    // Huntsman Knife Skins
    HUNTSMAN_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    HUNTSMAN_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    HUNTSMAN_KNIFE_FADE = 38, // Fade
    HUNTSMAN_KNIFE_NIGHT = 40, // Night
    HUNTSMAN_KNIFE_BLUE_STEEL = 42, // Blue Steel
    HUNTSMAN_KNIFE_STAINED = 43, // Stained
    HUNTSMAN_KNIFE_CASE_HARDENED = 44, // Case Hardened
    HUNTSMAN_KNIFE_SLAUGHTER = 59, // Slaughter
    HUNTSMAN_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    HUNTSMAN_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    HUNTSMAN_KNIFE_URBAN_MASKED = 143, // Urban Masked
    HUNTSMAN_KNIFE_SCORCHED = 175, // Scorched
    HUNTSMAN_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    HUNTSMAN_KNIFE_DAMASCUS_STEEL = 411, // Damascus Steel
    HUNTSMAN_KNIFE_MARBLE_FADE = 413, // Marble Fade
    HUNTSMAN_KNIFE_RUST_COAT = 414, // Rust Coat
    HUNTSMAN_KNIFE_DOPPLER = 417, // Doppler
    HUNTSMAN_KNIFE_GAMMA_DOPPLER = 568, // Gamma Doppler
    HUNTSMAN_KNIFE_BRIGHT_WATER = 579, // Bright Water
    HUNTSMAN_KNIFE_FREEHAND = 581, // Freehand
    HUNTSMAN_KNIFE_ULTRAVIOLET = 620, // Ultraviolet
    HUNTSMAN_KNIFE_LORE = 1107, // Lore
    HUNTSMAN_KNIFE_BLACK_LAMINATE = 1112, // Black Laminate
    HUNTSMAN_KNIFE_AUTOTRONIC = 1117, // Autotronic

    // Hydra Gloves Skins
    HYDRA_GLOVES_EMERALD = 10057, // Emerald
    HYDRA_GLOVES_MANGROVE = 10058, // Mangrove
    HYDRA_GLOVES_RATTLER = 10059, // Rattler
    HYDRA_GLOVES_CASE_HARDENED = 10060, // Case Hardened

    // Karambit Skins
    KARAMBIT_FOREST_DDPAT = 5, // Forest DDPAT
    KARAMBIT_CRIMSON_WEB = 12, // Crimson Web
    KARAMBIT_FADE = 38, // Fade
    KARAMBIT_NIGHT = 40, // Night
    KARAMBIT_BLUE_STEEL = 42, // Blue Steel
    KARAMBIT_STAINED = 43, // Stained
    KARAMBIT_CASE_HARDENED = 44, // Case Hardened
    KARAMBIT_SLAUGHTER = 59, // Slaughter
    KARAMBIT_SAFARI_MESH = 72, // Safari Mesh
    KARAMBIT_BOREAL_FOREST = 77, // Boreal Forest
    KARAMBIT_ULTRAVIOLET = 98, // Ultraviolet
    KARAMBIT_URBAN_MASKED = 143, // Urban Masked
    KARAMBIT_SCORCHED = 175, // Scorched
    KARAMBIT_TIGER_TOOTH = 409, // Tiger Tooth
    KARAMBIT_DAMASCUS_STEEL = 410, // Damascus Steel
    KARAMBIT_MARBLE_FADE = 413, // Marble Fade
    KARAMBIT_RUST_COAT = 414, // Rust Coat
    KARAMBIT_DOPPLER = 417, // Doppler
    KARAMBIT_LORE = 561, // Lore
    KARAMBIT_BLACK_LAMINATE = 566, // Black Laminate
    KARAMBIT_GAMMA_DOPPLER = 568, // Gamma Doppler
    KARAMBIT_AUTOTRONIC = 576, // Autotronic
    KARAMBIT_BRIGHT_WATER = 578, // Bright Water
    KARAMBIT_FREEHAND = 582, // Freehand

    // Kukri Knife Skins
    KUKRI_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    KUKRI_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    KUKRI_KNIFE_FADE = 38, // Fade
    KUKRI_KNIFE_BLUE_STEEL = 42, // Blue Steel
    KUKRI_KNIFE_STAINED = 43, // Stained
    KUKRI_KNIFE_CASE_HARDENED = 44, // Case Hardened
    KUKRI_KNIFE_SLAUGHTER = 59, // Slaughter
    KUKRI_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    KUKRI_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    KUKRI_KNIFE_URBAN_MASKED = 143, // Urban Masked
    KUKRI_KNIFE_SCORCHED = 175, // Scorched
    KUKRI_KNIFE_NIGHT_STRIPE = 735, // Night Stripe

    // M249 Skins
    M249_CONTRAST_SPRAY = 22, // Contrast Spray
    M249_BLIZZARD_MARBLEIZED = 75, // Blizzard Marbleized
    M249_HYPNOSIS = 120, // Hypnosis
    M249_JUNGLE = 151, // Jungle
    M249_PREDATOR = 170, // Predator
    M249_JUNGLE_DDPAT = 202, // Jungle DDPAT
    M249_GATOR_MESH = 243, // Gator Mesh
    M249_MAGMA = 266, // Magma
    M249_SYSTEM_LOCK = 401, // System Lock
    M249_SHIPPING_FORECAST = 452, // Shipping Forecast
    M249_IMPACT_DRILL = 472, // Impact Drill
    M249_NEBULA_CRUSADER = 496, // Nebula Crusader
    M249_SPECTRE = 547, // Spectre
    M249_EMERALD_POISON_DART = 648, // Emerald Poison Dart
    M249_HUMIDOR = 827, // Humidor
    M249_SPECTROGRAM = 875, // Spectrogram
    M249_WARBIRD = 900, // Warbird
    M249_AZTEC = 902, // Aztec
    M249_MIDNIGHT_PALM = 933, // Midnight Palm
    M249_DEEP_RELIEF = 983, // Deep Relief
    M249_OSIPR = 1042, // O.S.I.P.R.
    M249_DOWNTOWN = 1148, // Downtown
    M249_SUBMERGED = 1242, // Submerged
    M249_SAGE_CAMO = 1298, // Sage Camo

    // M4A1-S Skins
    M4A1_S_DARK_WATER = 60, // Dark Water
    M4A1_S_BOREAL_FOREST = 77, // Boreal Forest
    M4A1_S_VAPORWAVE = 106, // Vaporwave
    M4A1_S_WASH_ME_PLZ = 160, // Wash me plz
    M4A1_S_BRIGHT_WATER = 189, // Bright Water
    M4A1_S_BLOOD_TIGER = 217, // Blood Tiger
    M4A1_S_VARICAMO = 235, // VariCamo
    M4A1_S_NITRO = 254, // Nitro
    M4A1_S_GUARDIAN = 257, // Guardian
    M4A1_S_ATOMIC_ALLOY = 301, // Atomic Alloy
    M4A1_S_MASTER_PIECE = 321, // Master Piece
    M4A1_S_KNIGHT = 326, // Knight
    M4A1_S_CYREX = 360, // Cyrex
    M4A1_S_BASILISK = 383, // Basilisk
    M4A1_S_HYPER_BEAST = 430, // Hyper Beast
    M4A1_S_ICARUS_FELL = 440, // Icarus Fell
    M4A1_S_HOT_ROD = 445, // Hot Rod
    M4A1_S_GOLDEN_COIL = 497, // Golden Coil
    M4A1_S_CHANTICOS_FIRE = 548, // Chantico's Fire
    M4A1_S_MECHA_INDUSTRIES = 587, // Mecha Industries
    M4A1_S_FLASHBACK = 631, // Flashback
    M4A1_S_DECIMATOR = 644, // Decimator
    M4A1_S_BRIEFING = 663, // Briefing
    M4A1_S_LEADED_GLASS = 681, // Leaded Glass
    M4A1_S_NIGHTMARE = 714, // Nightmare
    M4A1_S_CONTROL_PANEL = 792, // Control Panel
    M4A1_S_MOSS_QUARTZ = 862, // Moss Quartz
    M4A1_S_PLAYER_TWO = 946, // Player Two
    M4A1_S_PRINTSTREAM = 984, // Printstream
    M4A1_S_WELCOME_TO_THE_JUNGLE = 1001, // Welcome to the Jungle
    M4A1_S_BLUE_PHOSPHOR = 1017, // Blue Phosphor
    M4A1_S_FIZZY_POP = 1059, // Fizzy POP
    M4A1_S_IMMINENT_DANGER = 1073, // Imminent Danger
    M4A1_S_NIGHT_TERROR = 1130, // Night Terror
    M4A1_S_BLACK_LOTUS = 1166, // Black Lotus
    M4A1_S_FADE = 1177, // Fade
    M4A1_S_STRATOSPHERE = 1216, // Stratosphere
    M4A1_S_EMPHOROSAUR_S = 1223, // Emphorosaur-S
    M4A1_S_MUD_SPEC = 1243, // Mud-Spec
    M4A1_S_GLITCHED_PAINT = 1311, // Glitched Paint
    M4A1_S_ROSE_HEX = 1319, // Rose Hex
    M4A1_S_SOLITUDE = 1338, // Solitude

    // M4A4 Skins
    M4A4_DESERT_STORM = 8, // Desert Storm
    M4A4_JUNGLE_TIGER = 16, // Jungle Tiger
    M4A4_URBAN_DDPAT = 17, // Urban DDPAT
    M4A4_TORNADO = 101, // Tornado
    M4A4_TURBINE = 118, // Turbine
    M4A4_BULLET_RAIN = 155, // Bullet Rain
    M4A4_MODERN_HUNTER = 164, // Modern Hunter
    M4A4_RADIATION_HAZARD = 167, // Radiation Hazard
    M4A4_FADED_ZEBRA = 176, // Faded Zebra
    M4A4_ZIRKA = 187, // Zirka
    M4A4_X_RAY = 215, // X-Ray
    M4A4_ASIIMOV = 255, // Asiimov
    M4A4_HOWL = 309, // Howl
    M4A4_DESERT_STRIKE = 336, // Desert-Strike
    M4A4_GRIFFIN = 384, // Griffin
    M4A4_DRAGON_KING = 400, // 龍王 (Dragon King)
    M4A4_POSEIDON = 449, // Poseidon
    M4A4_DAYBREAK = 471, // Daybreak
    M4A4_EVIL_DAIMYO = 480, // Evil Daimyo
    M4A4_ROYAL_PALADIN = 512, // Royal Paladin
    M4A4_THE_BATTLESTAR = 533, // The Battlestar
    M4A4_DESOLATE_SPACE = 588, // Desolate Space
    M4A4_BUZZ_KILL = 632, // Buzz Kill
    M4A4_HELLFIRE = 664, // Hellfire
    M4A4_NEO_NOIR = 695, // Neo-Noir
    M4A4_DARK_BLOSSOM = 730, // Dark Blossom
    M4A4_MAINFRAME = 780, // Mainframe
    M4A4_CONVERTER = 793, // Converter
    M4A4_MAGNESIUM = 811, // Magnesium
    M4A4_THE_EMPEROR = 844, // The Emperor
    M4A4_POLYSOUP = 874, // Polysoup
    M4A4_RED_DDPAT = 926, // Red DDPAT
    M4A4_TOOTH_FAIRY = 971, // Tooth Fairy
    M4A4_CYBER_SECURITY = 985, // Cyber Security
    M4A4_GLOBAL_OFFENSIVE = 993, // Global Offensive
    M4A4_IN_LIVING_COLOR = 1041, // In Living Color
    M4A4_THE_COALITION = 1063, // The Coalition
    M4A4_SPIDER_LILY = 1097, // Spider Lily
    M4A4_POLY_MAG = 1149, // Poly Mag
    M4A4_ETCH_LORD = 1165, // Etch Lord
    M4A4_HELLISH = 1209, // Hellish
    M4A4_CHOPPA = 1210, // Choppa
    M4A4_TEMUKAU = 1228, // Temukau
    M4A4_EYE_OF_HORUS = 1255, // Eye of Horus
    M4A4_NAVAL_SHRED_CAMO = 1266, // Naval Shred Camo
    M4A4_SHEET_LIGHTNING = 1281, // Sheet Lightning
    M4A4_STEEL_WORK = 1313, // Steel Work

    // M9 Bayonet Skins
    M9_BAYONET_FOREST_DDPAT = 5, // Forest DDPAT
    M9_BAYONET_CRIMSON_WEB = 12, // Crimson Web
    M9_BAYONET_FADE = 38, // Fade
    M9_BAYONET_NIGHT = 40, // Night
    M9_BAYONET_BLUE_STEEL = 42, // Blue Steel
    M9_BAYONET_STAINED = 43, // Stained
    M9_BAYONET_CASE_HARDENED = 44, // Case Hardened
    M9_BAYONET_SLAUGHTER = 59, // Slaughter
    M9_BAYONET_SAFARI_MESH = 72, // Safari Mesh
    M9_BAYONET_BOREAL_FOREST = 77, // Boreal Forest
    M9_BAYONET_ULTRAVIOLET = 98, // Ultraviolet
    M9_BAYONET_URBAN_MASKED = 143, // Urban Masked
    M9_BAYONET_SCORCHED = 175, // Scorched
    M9_BAYONET_TIGER_TOOTH = 409, // Tiger Tooth
    M9_BAYONET_DAMASCUS_STEEL = 411, // Damascus Steel
    M9_BAYONET_MARBLE_FADE = 413, // Marble Fade
    M9_BAYONET_RUST_COAT = 414, // Rust Coat
    M9_BAYONET_DOPPLER = 417, // Doppler
    M9_BAYONET_LORE = 562, // Lore
    M9_BAYONET_BLACK_LAMINATE = 567, // Black Laminate
    M9_BAYONET_GAMMA_DOPPLER = 568, // Gamma Doppler
    M9_BAYONET_AUTOTRONIC = 577, // Autotronic
    M9_BAYONET_BRIGHT_WATER = 579, // Bright Water
    M9_BAYONET_FREEHAND = 581, // Freehand

    // MAC-10 Skins
    MAC_10_CANDY_APPLE = 3, // Candy Apple
    MAC_10_URBAN_DDPAT = 17, // Urban DDPAT
    MAC_10_SILVER = 32, // Silver
    MAC_10_FADE = 38, // Fade
    MAC_10_CASE_HARDENED = 44, // Case Hardened
    MAC_10_ULTRAVIOLET = 98, // Ultraviolet
    MAC_10_TORNADO = 101, // Tornado
    MAC_10_SAIB_ONI = 126, // Saibā Oni
    MAC_10_PIPSQUEAK = 140, // Pipsqueak
    MAC_10_PALM = 157, // Palm
    MAC_10_GRAVEN = 188, // Graven
    MAC_10_AMBER_FADE = 246, // Amber Fade
    MAC_10_HEAT = 284, // Heat
    MAC_10_CURSE = 310, // Curse
    MAC_10_INDIGO = 333, // Indigo
    MAC_10_TATTER = 337, // Tatter
    MAC_10_COMMUTER = 343, // Commuter
    MAC_10_NUCLEAR_GARDEN = 372, // Nuclear Garden
    MAC_10_MALACHITE = 402, // Malachite
    MAC_10_NEON_RIDER = 433, // Neon Rider
    MAC_10_RANGEEN = 498, // Rangeen
    MAC_10_LAPIS_GATOR = 534, // Lapis Gator
    MAC_10_CARNIVORE = 589, // Carnivore
    MAC_10_LAST_DIVE = 651, // Last Dive
    MAC_10_ALOHA = 665, // Aloha
    MAC_10_OCEANIC = 682, // Oceanic
    MAC_10_RED_FILIGREE = 742, // Red Filigree
    MAC_10_CALF_SKIN = 748, // Calf Skin
    MAC_10_COPPER_BORRE = 761, // Copper Borre
    MAC_10_PIPE_DOWN = 812, // Pipe Down
    MAC_10_SIENNA_DAMASK = 826, // Sienna Damask
    MAC_10_WHITEFISH = 840, // Whitefish
    MAC_10_SURFWOOD = 871, // Surfwood
    MAC_10_STALKER = 898, // Stalker
    MAC_10_CLASSIC_CRATE = 908, // Classic Crate
    MAC_10_DISCO_TECH = 947, // Disco Tech
    MAC_10_ALLURE = 965, // Allure
    MAC_10_HOT_SNAKES = 1009, // Hot Snakes
    MAC_10_GOLD_BRICK = 1025, // Gold Brick
    MAC_10_BUTTON_MASHER = 1045, // Button Masher
    MAC_10_PROPAGANDA = 1067, // Propaganda
    MAC_10_STRATS = 1075, // Strats
    MAC_10_TOYBOX = 1098, // Toybox
    MAC_10_ENSNARED = 1131, // Ensnared
    MAC_10_MONKEYFLAGE = 1150, // Monkeyflage
    MAC_10_LIGHT_BOX = 1164, // Light Box
    MAC_10_DERAILMENT = 1204, // Derailment
    MAC_10_SAKKAKU = 1229, // Sakkaku
    MAC_10_ECHOING_SANDS = 1244, // Echoing Sands
    MAC_10_STORM_CAMO = 1269, // Storm Camo
    MAC_10_POPLAR_THICKET = 1285, // Poplar Thicket
    MAC_10_ACID_HEX = 1295, // Acid Hex
    MAC_10_BRONZER = 1334, // Bronzer

    // MAG-7 Skins
    MAG_7_SILVER = 32, // Silver
    MAG_7_METALLIC_DDPAT = 34, // Metallic DDPAT
    MAG_7_BULLDOZER = 39, // Bulldozer
    MAG_7_CARBON_FIBER = 70, // Carbon Fiber
    MAG_7_SAND_DUNE = 99, // Sand Dune
    MAG_7_STORM = 100, // Storm
    MAG_7_IRRADIATED_ALERT = 171, // Irradiated Alert
    MAG_7_MEMENTO = 177, // Memento
    MAG_7_HAZARD = 198, // Hazard
    MAG_7_HEAVEN_GUARD = 291, // Heaven Guard
    MAG_7_CHAINMAIL = 327, // Chainmail
    MAG_7_FIRESTARTER = 385, // Firestarter
    MAG_7_HEAT = 431, // Heat
    MAG_7_COUNTER_TERRACE = 462, // Counter Terrace
    MAG_7_SEABIRD = 473, // Seabird
    MAG_7_COBALT_CORE = 499, // Cobalt Core
    MAG_7_PRAETORIAN = 535, // Praetorian
    MAG_7_PETROGLYPH = 608, // Petroglyph
    MAG_7_SONAR = 633, // Sonar
    MAG_7_HARD_WATER = 666, // Hard Water
    MAG_7_SWAG_7 = 703, // SWAG-7
    MAG_7_CINQUEDEA = 737, // Cinquedea
    MAG_7_RUST_COAT = 754, // Rust Coat
    MAG_7_WILDWOOD = 773, // Wildwood
    MAG_7_CORE_BREACH = 787, // Core Breach
    MAG_7_NAVY_SHEEN = 822, // Navy Sheen
    MAG_7_POPDOG = 909, // Popdog
    MAG_7_JUSTICE = 948, // Justice
    MAG_7_MONSTER_CALL = 961, // Monster Call
    MAG_7_PRISM_TERRACE = 1072, // Prism Terrace
    MAG_7_BI83_SPECTRUM = 1089, // BI83 Spectrum
    MAG_7_FORESIGHT = 1132, // Foresight
    MAG_7_RESUPPLY = 1188, // Resupply
    MAG_7_INSOMNIA = 1220, // Insomnia
    MAG_7_COPPER_COATED = 1245, // Copper Coated
    MAG_7_COPPER_OXIDE = 1306, // Copper Oxide

    // MP5-SD Skins
    MP5_SD_NEON_SQUEEZER = 161, // Neon Squeezer
    MP5_SD_DIRT_DROP = 753, // Dirt Drop
    MP5_SD_SAVANNAH_HALFTONE = 768, // Savannah Halftone
    MP5_SD_CO_PROCESSOR = 781, // Co-Processor
    MP5_SD_NITRO = 798, // Nitro
    MP5_SD_LAB_RATS = 800, // Lab Rats
    MP5_SD_PHOSPHOR = 810, // Phosphor
    MP5_SD_GAUSS = 846, // Gauss
    MP5_SD_BAMBOO_GARDEN = 872, // Bamboo Garden
    MP5_SD_ACID_WASH = 888, // Acid Wash
    MP5_SD_AGENT = 915, // Agent
    MP5_SD_OXIDE_OASIS = 923, // Oxide Oasis
    MP5_SD_DESERT_STRIKE = 949, // Desert Strike
    MP5_SD_KITBASH = 974, // Kitbash
    MP5_SD_CONDITION_ZERO = 986, // Condition Zero
    MP5_SD_AUTUMN_TWILLY = 1061, // Autumn Twilly
    MP5_SD_NECRO_JR = 1137, // Necro Jr.
    MP5_SD_STATICS = 1180, // Statics
    MP5_SD_LIQUIDATION = 1231, // Liquidation
    MP5_SD_LIME_HEX = 1274, // Lime Hex
    MP5_SD_GOLD_LEAF = 1294, // Gold Leaf

    // MP7 Skins
    MP7_FOREST_DDPAT = 5, // Forest DDPAT
    MP7_SKULLS = 11, // Skulls
    MP7_GUNSMOKE = 15, // Gunsmoke
    MP7_ANODIZED_NAVY = 28, // Anodized Navy
    MP7_WHITEOUT = 102, // Whiteout
    MP7_ORANGE_PEEL = 141, // Orange Peel
    MP7_SCORCHED = 175, // Scorched
    MP7_GROUNDWATER = 209, // Groundwater
    MP7_OCEAN_FOAM = 213, // Ocean Foam
    MP7_ARMY_RECON = 245, // Army Recon
    MP7_FULL_STOP = 250, // Full Stop
    MP7_URBAN_HAZARD = 354, // Urban Hazard
    MP7_OLIVE_PLAID = 365, // Olive Plaid
    MP7_ARMOR_CORE = 423, // Armor Core
    MP7_ASTERION = 442, // Asterion
    MP7_NEMESIS = 481, // Nemesis
    MP7_SPECIAL_DELIVERY = 500, // Special Delivery
    MP7_IMPIRE = 536, // Impire
    MP7_CIRRUS = 627, // Cirrus
    MP7_AKOBEN = 649, // Akoben
    MP7_BLOODSPORT = 696, // Bloodsport
    MP7_POWERCORE = 719, // Powercore
    MP7_TEAL_BLOSSOM = 728, // Teal Blossom
    MP7_FADE = 752, // Fade
    MP7_MOTHERBOARD = 782, // Motherboard
    MP7_MISCHIEF = 847, // Mischief
    MP7_NEON_PLY = 893, // Neon Ply
    MP7_PREY = 935, // Prey
    MP7_ASTROLABE = 940, // Astrolabe
    MP7_VAULT_HEIST = 1007, // Vault Heist
    MP7_TALL_GRASS = 1023, // Tall Grass
    MP7_GUERRILLA = 1096, // Guerrilla
    MP7_ABYSSAL_APPARITION = 1133, // Abyssal Apparition
    MP7_JUST_SMILE = 1163, // Just Smile
    MP7_SUNBAKED = 1246, // Sunbaked
    MP7_SHORT_OCHRE = 1326, // Short Ochre

    // MP9 Skins
    MP9_HOT_ROD = 33, // Hot Rod
    MP9_BULLDOZER = 39, // Bulldozer
    MP9_HYPNOTIC = 61, // Hypnotic
    MP9_STORM = 100, // Storm
    MP9_ORANGE_PEEL = 141, // Orange Peel
    MP9_SAND_DASHED = 148, // Sand Dashed
    MP9_DRY_SEASON = 199, // Dry Season
    MP9_ROSE_IRON = 262, // Rose Iron
    MP9_ARMY_SHEEN = 298, // Army Sheen
    MP9_DARK_AGE = 329, // Dark Age
    MP9_ARCTIC_TRI_TONE = 331, // Arctic Tri-Tone
    MP9_GREEN_PLAID = 366, // Green Plaid
    MP9_SETTING_SUN = 368, // Setting Sun
    MP9_DART = 386, // Dart
    MP9_DEADLY_POISON = 403, // Deadly Poison
    MP9_PANDORAS_BOX = 448, // Pandora's Box
    MP9_RUBY_POISON_DART = 482, // Ruby Poison Dart
    MP9_BIOLEAK = 549, // Bioleak
    MP9_AIRLOCK = 609, // Airlock
    MP9_SAND_SCALE = 630, // Sand Scale
    MP9_GOO = 679, // Goo
    MP9_BLACK_SAND = 697, // Black Sand
    MP9_CAPILLARY = 715, // Capillary
    MP9_WILD_LILY = 734, // Wild Lily
    MP9_SLIDE = 755, // Slide
    MP9_MODEST_THREAT = 804, // Modest Threat
    MP9_MUSIC_BOX = 820, // Music Box
    MP9_STAINED_GLASS = 867, // Stained Glass
    MP9_HYDRA = 910, // Hydra
    MP9_OLD_ROOTS = 931, // Old Roots
    MP9_FOOD_CHAIN = 1037, // Food Chain
    MP9_MOUNT_FUJI = 1094, // Mount Fuji
    MP9_STARLIGHT_PROTECTOR = 1134, // Starlight Protector
    MP9_NEXUS = 1193, // Nexus
    MP9_LATTE_RUSH = 1211, // Latte Rush
    MP9_FEATHERWEIGHT = 1225, // Featherweight
    MP9_COBALT_PAISLEY = 1258, // Cobalt Paisley
    MP9_BUFF_BLUE = 1278, // Buff Blue
    MP9_PINE = 1301, // Pine
    MP9_SHREDDED = 1310, // Shredded
    MP9_MULTI_TERRAIN = 1330, // Multi-Terrain

    // Moto Gloves Skins
    MOTO_GLOVES_ECLIPSE = 10024, // Eclipse
    MOTO_GLOVES_SPEARMINT = 10026, // Spearmint
    MOTO_GLOVES_BOOM = 10027, // Boom!
    MOTO_GLOVES_COOL_MINT = 10028, // Cool Mint
    MOTO_GLOVES_POW = 10049, // POW!
    MOTO_GLOVES_TURTLE = 10050, // Turtle
    MOTO_GLOVES_TRANSPORT = 10051, // Transport
    MOTO_GLOVES_POLYGON = 10052, // Polygon
    MOTO_GLOVES_FINISH_LINE = 10077, // Finish Line
    MOTO_GLOVES_SMOKE_OUT = 10078, // Smoke Out
    MOTO_GLOVES_BLOOD_PRESSURE = 10079, // Blood Pressure
    MOTO_GLOVES_3RD_COMMANDO_COMPANY = 10080, // 3rd Commando Company

    // Navaja Knife Skins
    NAVAJA_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    NAVAJA_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    NAVAJA_KNIFE_FADE = 38, // Fade
    NAVAJA_KNIFE_BLUE_STEEL = 42, // Blue Steel
    NAVAJA_KNIFE_STAINED = 43, // Stained
    NAVAJA_KNIFE_CASE_HARDENED = 44, // Case Hardened
    NAVAJA_KNIFE_SLAUGHTER = 59, // Slaughter
    NAVAJA_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    NAVAJA_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    NAVAJA_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    NAVAJA_KNIFE_URBAN_MASKED = 143, // Urban Masked
    NAVAJA_KNIFE_SCORCHED = 175, // Scorched
    NAVAJA_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    NAVAJA_KNIFE_MARBLE_FADE = 413, // Marble Fade
    NAVAJA_KNIFE_RUST_COAT = 414, // Rust Coat
    NAVAJA_KNIFE_DOPPLER = 417, // Doppler
    NAVAJA_KNIFE_NIGHT_STRIPE = 735, // Night Stripe
    NAVAJA_KNIFE_DAMASCUS_STEEL = 857, // Damascus Steel

    // Negev Skins
    NEGEV_ANODIZED_NAVY = 28, // Anodized Navy
    NEGEV_WALL_BANG = 144, // Wall Bang
    NEGEV_PALM = 201, // Palm
    NEGEV_CALICAMO = 240, // CaliCamo
    NEGEV_TERRAIN = 285, // Terrain
    NEGEV_ARMY_SHEEN = 298, // Army Sheen
    NEGEV_BRATATAT = 317, // Bratatat
    NEGEV_DESERT_STRIKE = 355, // Desert-Strike
    NEGEV_NUCLEAR_WASTE = 369, // Nuclear Waste
    NEGEV_MAN_O_WAR = 432, // Man-o'-war
    NEGEV_LOUDMOUTH = 483, // Loudmouth
    NEGEV_POWER_LOADER = 514, // Power Loader
    NEGEV_DAZZLE = 610, // Dazzle
    NEGEV_LIONFISH = 698, // Lionfish
    NEGEV_MJLNIR = 763, // Mjölnir
    NEGEV_BULKHEAD = 783, // Bulkhead
    NEGEV_BOROQUE_SAND = 920, // Boroque Sand
    NEGEV_PROTOTYPE = 950, // Prototype
    NEGEV_ULTRALIGHT = 958, // Ultralight
    NEGEV_PHOENIX_STENCIL = 1012, // Phoenix Stencil
    NEGEV_DEV_TEXTURE = 1043, // dev_texture
    NEGEV_INFRASTRUCTURE = 1080, // Infrastructure
    NEGEV_DROP_ME = 1152, // Drop Me
    NEGEV_SOUR_GRAPES = 1260, // Sour Grapes
    NEGEV_RAW_CERAMIC = 1300, // Raw Ceramic

    // Nomad Knife Skins
    NOMAD_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    NOMAD_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    NOMAD_KNIFE_FADE = 38, // Fade
    NOMAD_KNIFE_BLUE_STEEL = 42, // Blue Steel
    NOMAD_KNIFE_STAINED = 43, // Stained
    NOMAD_KNIFE_CASE_HARDENED = 44, // Case Hardened
    NOMAD_KNIFE_SLAUGHTER = 59, // Slaughter
    NOMAD_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    NOMAD_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    NOMAD_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    NOMAD_KNIFE_URBAN_MASKED = 143, // Urban Masked
    NOMAD_KNIFE_SCORCHED = 175, // Scorched
    NOMAD_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    NOMAD_KNIFE_DAMASCUS_STEEL = 410, // Damascus Steel
    NOMAD_KNIFE_MARBLE_FADE = 413, // Marble Fade
    NOMAD_KNIFE_RUST_COAT = 414, // Rust Coat
    NOMAD_KNIFE_DOPPLER = 417, // Doppler
    NOMAD_KNIFE_NIGHT_STRIPE = 735, // Night Stripe

    // Nova Skins
    NOVA_CANDY_APPLE = 3, // Candy Apple
    NOVA_FOREST_LEAVES = 25, // Forest Leaves
    NOVA_BLOOMSTICK = 62, // Bloomstick
    NOVA_SAND_DUNE = 99, // Sand Dune
    NOVA_POLAR_MESH = 107, // Polar Mesh
    NOVA_WURST_HLLE = 145, // Wurst Hölle
    NOVA_WALNUT = 158, // Walnut
    NOVA_MODERN_HUNTER = 164, // Modern Hunter
    NOVA_BLAZE_ORANGE = 166, // Blaze Orange
    NOVA_PREDATOR = 170, // Predator
    NOVA_TEMPEST = 191, // Tempest
    NOVA_GRAPHITE = 214, // Graphite
    NOVA_GHOST_CAMO = 225, // Ghost Camo
    NOVA_RED_QUARTZ = 248, // Red Quartz
    NOVA_RISING_SKULL = 263, // Rising Skull
    NOVA_ANTIQUE = 286, // Antique
    NOVA_GREEN_APPLE = 294, // Green Apple
    NOVA_ARMY_SHEEN = 298, // Army Sheen
    NOVA_CAGED_STEEL = 299, // Caged Steel
    NOVA_RUST_COAT = 323, // Rust Coat
    NOVA_YORKSHIRE = 324, // Yorkshire
    NOVA_KOI = 356, // Koi
    NOVA_MOON_IN_LIBRA = 450, // Moon in Libra
    NOVA_RANGER = 484, // Ranger
    NOVA_HYPER_BEAST = 537, // Hyper Beast
    NOVA_EXO = 590, // Exo
    NOVA_GILA = 634, // Gila
    NOVA_WILD_SIX = 699, // Wild Six
    NOVA_TOY_SOLDIER = 716, // Toy Soldier
    NOVA_BAROQUE_ORANGE = 746, // Baroque Orange
    NOVA_MANDREL = 785, // Mandrel
    NOVA_WOOD_FIRED = 809, // Wood Fired
    NOVA_PLUME = 890, // Plume
    NOVA_QUICK_SAND = 929, // Quick Sand
    NOVA_CLEAR_POLYMER = 987, // Clear Polymer
    NOVA_WINDBLOWN = 1051, // Windblown
    NOVA_INTERLOCK = 1077, // Interlock
    NOVA_DARK_SIGIL = 1162, // Dark Sigil
    NOVA_RISING_SUN = 1192, // Rising Sun
    NOVA_SOBEKS_BITE = 1247, // Sobek's Bite
    NOVA_TURQUOISE_POUR = 1261, // Turquoise Pour
    NOVA_MARSH_GRASS = 1331, // Marsh Grass
    NOVA_RAIN_STATION = 1337, // Rain Station

    // P2000 Skins
    P2000_GRANITE_MARBLEIZED = 21, // Granite Marbleized
    P2000_SILVER = 32, // Silver
    P2000_SCORPION = 71, // Scorpion
    P2000_GRASSLAND = 95, // Grassland
    P2000_GRASSLAND_LEAVES = 104, // Grassland Leaves
    P2000_CORTICERA = 184, // Corticera
    P2000_OCEAN_FOAM = 211, // Ocean Foam
    P2000_AMBER_FADE = 246, // Amber Fade
    P2000_RED_FRAGCAM = 275, // Red FragCam
    P2000_CHAINMAIL = 327, // Chainmail
    P2000_PULSE = 338, // Pulse
    P2000_COACH_CLASS = 346, // Coach Class
    P2000_IVORY = 357, // Ivory
    P2000_FIRE_ELEMENTAL = 389, // Fire Elemental
    P2000_PATHFINDER = 443, // Pathfinder
    P2000_HANDGUN = 485, // Handgun
    P2000_IMPERIAL = 515, // Imperial
    P2000_OCEANIC = 550, // Oceanic
    P2000_IMPERIAL_DRAGON = 591, // Imperial Dragon
    P2000_TURF = 635, // Turf
    P2000_WOODSMAN = 667, // Woodsman
    P2000_URBAN_HAZARD = 700, // Urban Hazard
    P2000_CORAL_HALFTONE = 878, // Coral Halftone
    P2000_OBSIDIAN = 894, // Obsidian
    P2000_ACID_ETCHED = 951, // Acid Etched
    P2000_GNARLED = 960, // Gnarled
    P2000_DISPATCH = 997, // Dispatch
    P2000_PANTHER_CAMO = 1019, // Panther Camo
    P2000_SPACE_RACE = 1055, // Space Race
    P2000_LIFTED_SPIRITS = 1138, // Lifted Spirits
    P2000_SURE_GRIP = 1181, // Sure Grip
    P2000_WICKED_SICK = 1224, // Wicked Sick
    P2000_ROYAL_BAROQUE = 1259, // Royal Baroque
    P2000_MARSH = 1292, // Marsh

    // P250 Skins
    P250_GUNSMOKE = 15, // Gunsmoke
    P250_BONE_MASK = 27, // Bone Mask
    P250_METALLIC_DDPAT = 34, // Metallic DDPAT
    P250_BOREAL_FOREST = 77, // Boreal Forest
    P250_FOREST_NIGHT = 78, // Forest Night
    P250_SAND_DUNE = 99, // Sand Dune
    P250_WHITEOUT = 102, // Whiteout
    P250_X_RAY = 125, // X-Ray
    P250_EPICENTER = 130, // Epicenter
    P250_SPLASH = 162, // Splash
    P250_MODERN_HUNTER = 164, // Modern Hunter
    P250_NUCLEAR_THREAT = 168, // Nuclear Threat
    P250_FACETS = 207, // Facets
    P250_HIVE = 219, // Hive
    P250_STEEL_DISRUPTION = 230, // Steel Disruption
    P250_MEHNDI = 258, // Mehndi
    P250_UNDERTOW = 271, // Undertow
    P250_FRANKLIN = 295, // Franklin
    P250_SUPERNOVA = 358, // Supernova
    P250_CONTAMINATION = 373, // Contamination
    P250_CARTEL = 388, // Cartel
    P250_MUERTOS = 404, // Muertos
    P250_VALENCE = 426, // Valence
    P250_CRIMSON_KIMONO = 466, // Crimson Kimono
    P250_MINT_KIMONO = 467, // Mint Kimono
    P250_WINGSHOT = 501, // Wingshot
    P250_ASIIMOV = 551, // Asiimov
    P250_IRON_CLAD = 592, // Iron Clad
    P250_RIPPLE = 650, // Ripple
    P250_RED_ROCK = 668, // Red Rock
    P250_SEE_YA_LATER = 678, // See Ya Later
    P250_DARK_FILIGREE = 741, // Dark Filigree
    P250_VINO_PRIMO = 749, // Vino Primo
    P250_SMALL_GAME = 774, // Small Game
    P250_FACILITY_DRAFT = 777, // Facility Draft
    P250_EXCHANGER = 786, // Exchanger
    P250_NEVERMORE = 813, // Nevermore
    P250_DROUGHT = 825, // Drought
    P250_VERDIGRIS = 848, // Verdigris
    P250_INFERNO = 907, // Inferno
    P250_BLACK_TAN = 928, // Black & Tan
    P250_CASSETTE = 968, // Cassette
    P250_CONTAMINANT = 982, // Contaminant
    P250_BENGAL_TIGER = 1030, // Bengal Tiger
    P250_CYBER_SHELL = 1044, // Cyber Shell
    P250_DIGITAL_ARCHITECT = 1081, // Digital Architect
    P250_VISIONS = 1153, // Visions
    P250_CONSTRUCTIVIST = 1212, // Constructivist
    P250_REBUILT = 1230, // Re.built
    P250_APEPS_CURSE = 1248, // Apep's Curse
    P250_PLUM_NETTING = 1273, // Plum Netting
    P250_COPPER_OXIDE = 1307, // Copper Oxide
    P250_RED_TIDE = 1315, // Red Tide
    P250_SEDIMENTARY = 1317, // Sedimentary

    // P90 Skins
    P90_VIRUS = 20, // Virus
    P90_COLD_BLOODED = 67, // Cold Blooded
    P90_STORM = 100, // Storm
    P90_GLACIER_MESH = 111, // Glacier Mesh
    P90_SAND_SPRAY = 124, // Sand Spray
    P90_RANDY_RUSH = 127, // Randy Rush
    P90_WASH_ME = 133, // Wash me
    P90_DEATH_BY_KITTY = 156, // Death by Kitty
    P90_FALLOUT_WARNING = 169, // Fallout Warning
    P90_SCORCHED = 175, // Scorched
    P90_EMERALD_DRAGON = 182, // Emerald Dragon
    P90_BLIND_SPOT = 228, // Blind Spot
    P90_ASH_WOOD = 234, // Ash Wood
    P90_TEARDOWN = 244, // Teardown
    P90_TRIGON = 283, // Trigon
    P90_DESERT_WARFARE = 311, // Desert Warfare
    P90_MODULE = 335, // Module
    P90_LEATHER = 342, // Leather
    P90_ASIIMOV = 359, // Asiimov
    P90_ELITE_BUILD = 486, // Elite Build
    P90_SHAPEWOOD = 516, // Shapewood
    P90_CHOPPER = 593, // Chopper
    P90_GRIM = 611, // Grim
    P90_SHALLOW_GRAVE = 636, // Shallow Grave
    P90_DEATH_GRIP = 669, // Death Grip
    P90_TRACTION = 717, // Traction
    P90_SUNSET_LILY = 726, // Sunset Lily
    P90_BAROQUE_RED = 744, // Baroque Red
    P90_ASTRAL_JRMUNGANDR = 759, // Astral Jörmungandr
    P90_FACILITY_NEGATIVE = 776, // Facility Negative
    P90_VERDANT_GROWTH = 828, // Verdant Growth
    P90_OFF_WORLD = 849, // Off World
    P90_NOSTALGIA = 911, // Nostalgia
    P90_DESERT_DDPAT = 925, // Desert DDPAT
    P90_ATTACK_VECTOR = 936, // Attack Vector
    P90_FREIGHT = 969, // Freight
    P90_COCOA_RAMPAGE = 977, // Cocoa Rampage
    P90_RUN_AND_HIDE = 1000, // Run and Hide
    P90_TIGER_PIT = 1015, // Tiger Pit
    P90_ANCIENT_EARTH = 1020, // Ancient Earth
    P90_SCHEMATIC = 1074, // Schematic
    P90_VENT_RUSH = 1154, // Vent Rush
    P90_WAVE_BREAKER = 1190, // Wave Breaker
    P90_STRAIGHT_DIMES = 1199, // Straight Dimes
    P90_NEOQUEEN = 1233, // Neoqueen
    P90_SCARAB_RUSH = 1250, // ScaraB Rush
    P90_REEF_GRIEF = 1256, // Reef Grief
    P90_BLUE_TAC = 1277, // Blue Tac
    P90_MUSTARD_GAS = 1291, // Mustard Gas
    P90_DESERT_HALFTONE = 1332, // Desert Halftone

    // PP-Bizon Skins
    PP_BIZON_CANDY_APPLE = 3, // Candy Apple
    PP_BIZON_BLUE_STREAK = 13, // Blue Streak
    PP_BIZON_FOREST_LEAVES = 25, // Forest Leaves
    PP_BIZON_CARBON_FIBER = 70, // Carbon Fiber
    PP_BIZON_SAND_DASHED = 148, // Sand Dashed
    PP_BIZON_URBAN_DASHED = 149, // Urban Dashed
    PP_BIZON_BRASS = 159, // Brass
    PP_BIZON_MODERN_HUNTER = 164, // Modern Hunter
    PP_BIZON_IRRADIATED_ALERT = 171, // Irradiated Alert
    PP_BIZON_RUST_COAT = 203, // Rust Coat
    PP_BIZON_WATER_SIGIL = 224, // Water Sigil
    PP_BIZON_NIGHT_OPS = 236, // Night Ops
    PP_BIZON_COBALT_HALFTONE = 267, // Cobalt Halftone
    PP_BIZON_DEATH_RATTLE = 293, // Death Rattle
    PP_BIZON_ANTIQUE = 306, // Antique
    PP_BIZON_OSIRIS = 349, // Osiris
    PP_BIZON_CHEMICAL_GREEN = 376, // Chemical Green
    PP_BIZON_BAMBOO_PRINT = 457, // Bamboo Print
    PP_BIZON_FUEL_ROD = 508, // Fuel Rod
    PP_BIZON_PHOTIC_ZONE = 526, // Photic Zone
    PP_BIZON_JUDGEMENT_OF_ANUBIS = 542, // Judgement of Anubis
    PP_BIZON_HARVESTER = 594, // Harvester
    PP_BIZON_JUNGLE_SLIPSTREAM = 641, // Jungle Slipstream
    PP_BIZON_HIGH_ROLLER = 676, // High Roller
    PP_BIZON_NIGHT_RIOT = 692, // Night Riot
    PP_BIZON_COLD_CELL = 770, // Cold Cell
    PP_BIZON_FACILITY_SKETCH = 775, // Facility Sketch
    PP_BIZON_ANOLIS = 829, // Anolis
    PP_BIZON_SEABIRD = 873, // Seabird
    PP_BIZON_EMBARGO = 884, // Embargo
    PP_BIZON_RUNIC = 973, // Runic
    PP_BIZON_BREAKER_BOX = 1083, // Breaker Box
    PP_BIZON_LUMEN = 1099, // Lumen
    PP_BIZON_SPACE_CAT = 1125, // Space Cat
    PP_BIZON_WOOD_BLOCK_CAMO = 1325, // Wood Block Camo

    // Paracord Knife Skins
    PARACORD_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    PARACORD_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    PARACORD_KNIFE_FADE = 38, // Fade
    PARACORD_KNIFE_BLUE_STEEL = 42, // Blue Steel
    PARACORD_KNIFE_STAINED = 43, // Stained
    PARACORD_KNIFE_CASE_HARDENED = 44, // Case Hardened
    PARACORD_KNIFE_SLAUGHTER = 59, // Slaughter
    PARACORD_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    PARACORD_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    PARACORD_KNIFE_URBAN_MASKED = 143, // Urban Masked
    PARACORD_KNIFE_SCORCHED = 175, // Scorched
    PARACORD_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    PARACORD_KNIFE_DAMASCUS_STEEL = 410, // Damascus Steel
    PARACORD_KNIFE_MARBLE_FADE = 413, // Marble Fade
    PARACORD_KNIFE_RUST_COAT = 414, // Rust Coat
    PARACORD_KNIFE_DOPPLER = 417, // Doppler
    PARACORD_KNIFE_ULTRAVIOLET = 621, // Ultraviolet
    PARACORD_KNIFE_NIGHT_STRIPE = 735, // Night Stripe

    // R8 Revolver Skins
    R8_REVOLVER_CRIMSON_WEB = 12, // Crimson Web
    R8_REVOLVER_BONE_MASK = 27, // Bone Mask
    R8_REVOLVER_BLAZE = 37, // Blaze
    R8_REVOLVER_NIGHT = 40, // Night
    R8_REVOLVER_TANGO = 123, // Tango
    R8_REVOLVER_FADE = 522, // Fade
    R8_REVOLVER_AMBER_FADE = 523, // Amber Fade
    R8_REVOLVER_REBOOT = 595, // Reboot
    R8_REVOLVER_LLAMA_CANNON = 683, // Llama Cannon
    R8_REVOLVER_GRIP = 701, // Grip
    R8_REVOLVER_SURVIVALIST = 721, // Survivalist
    R8_REVOLVER_NITRO = 798, // Nitro
    R8_REVOLVER_SKULL_CRUSHER = 843, // Skull Crusher
    R8_REVOLVER_CANAL_SPRAY = 866, // Canal Spray
    R8_REVOLVER_MEMENTO = 892, // Memento
    R8_REVOLVER_DESERT_BRUSH = 924, // Desert Brush
    R8_REVOLVER_BONE_FORGED = 952, // Bone Forged
    R8_REVOLVER_PHOENIX_MARKER = 1011, // Phoenix Marker
    R8_REVOLVER_JUNK_YARD = 1047, // Junk Yard
    R8_REVOLVER_CRAZY_8 = 1145, // Crazy 8
    R8_REVOLVER_BANANA_CANNON = 1232, // Banana Cannon
    R8_REVOLVER_INLAY = 1237, // Inlay
    R8_REVOLVER_COBALT_GRIP = 1276, // Cobalt Grip
    R8_REVOLVER_LEAFHOPPER = 1293, // Leafhopper

    // SCAR-20 Skins
    SCAR_20_CONTRACTOR = 46, // Contractor
    SCAR_20_CARBON_FIBER = 70, // Carbon Fiber
    SCAR_20_STORM = 100, // Storm
    SCAR_20_SAND_MESH = 116, // Sand Mesh
    SCAR_20_TRAIL_BLAZER = 117, // Trail Blazer
    SCAR_20_PALM = 157, // Palm
    SCAR_20_BRASS = 159, // Brass
    SCAR_20_SPLASH_JAM = 165, // Splash Jam
    SCAR_20_EMERALD = 196, // Emerald
    SCAR_20_CRIMSON_WEB = 232, // Crimson Web
    SCAR_20_ARMY_SHEEN = 298, // Army Sheen
    SCAR_20_CYREX = 312, // Cyrex
    SCAR_20_CARDIAC = 391, // Cardiac
    SCAR_20_GROTTO = 406, // Grotto
    SCAR_20_GREEN_MARINE = 502, // Green Marine
    SCAR_20_OUTBREAK = 518, // Outbreak
    SCAR_20_BLOODSPORT = 597, // Bloodsport
    SCAR_20_POWERCORE = 612, // Powercore
    SCAR_20_BLUEPRINT = 642, // Blueprint
    SCAR_20_JUNGLE_SLIPSTREAM = 685, // Jungle Slipstream
    SCAR_20_STONE_MOSAICO = 865, // Stone Mosaico
    SCAR_20_WILD_BERRY = 883, // Wild Berry
    SCAR_20_TORN = 896, // Torn
    SCAR_20_ASSAULT = 914, // Assault
    SCAR_20_ENFORCER = 954, // Enforcer
    SCAR_20_MAGNA_CARTA = 1028, // Magna Carta
    SCAR_20_POULTRYGEIST = 1139, // Poultrygeist
    SCAR_20_FRAGMENTS = 1226, // Fragments
    SCAR_20_SHORT_OCHRE = 1327, // Short Ochre

    // SG 553 Skins
    SG_553_ANODIZED_NAVY = 28, // Anodized Navy
    SG_553_BULLDOZER = 39, // Bulldozer
    SG_553_HYPNOTIC = 61, // Hypnotic
    SG_553_ULTRAVIOLET = 98, // Ultraviolet
    SG_553_TORNADO = 101, // Tornado
    SG_553_WAVES_PERFORATED = 136, // Waves Perforated
    SG_553_WAVE_SPRAY = 186, // Wave Spray
    SG_553_GATOR_MESH = 243, // Gator Mesh
    SG_553_DAMASCUS_STEEL = 247, // Damascus Steel
    SG_553_PULSE = 287, // Pulse
    SG_553_ARMY_SHEEN = 298, // Army Sheen
    SG_553_TRAVELER = 363, // Traveler
    SG_553_FALLOUT_WARNING = 378, // Fallout Warning
    SG_553_CYREX = 487, // Cyrex
    SG_553_TIGER_MOTH = 519, // Tiger Moth
    SG_553_ATLAS = 553, // Atlas
    SG_553_AERIAL = 598, // Aerial
    SG_553_TRIARCH = 613, // Triarch
    SG_553_PHANTOM = 686, // Phantom
    SG_553_ALOHA = 702, // Aloha
    SG_553_INTEGRALE = 750, // Integrale
    SG_553_DESERT_BLOSSOM = 765, // Desert Blossom
    SG_553_DANGER_CLOSE = 815, // Danger Close
    SG_553_BARRICADE = 861, // Barricade
    SG_553_CANDY_APPLE = 864, // Candy Apple
    SG_553_COLONY_IV = 897, // Colony IV
    SG_553_BERRY_GEL_COAT = 901, // Berry Gel Coat
    SG_553_BLEACHED = 934, // Bleached
    SG_553_DARKWING = 955, // Darkwing
    SG_553_OL_RUSTY = 966, // Ol' Rusty
    SG_553_LUSH_RUINS = 1022, // Lush Ruins
    SG_553_HEAVY_METAL = 1048, // Heavy Metal
    SG_553_HAZARD_PAY = 1084, // Hazard Pay
    SG_553_DRAGON_TECH = 1151, // Dragon Tech
    SG_553_CYBERFORCE = 1234, // Cyberforce
    SG_553_NIGHT_CAMO = 1270, // Night Camo
    SG_553_BASKET_HALFTONE = 1320, // Basket Halftone

    // SSG 08 Skins
    SSG_08_LICHEN_DASHED = 26, // Lichen Dashed
    SSG_08_DARK_WATER = 60, // Dark Water
    SSG_08_CARBON_FIBER = 70, // Carbon Fiber
    SSG_08_BLUE_SPRUCE = 96, // Blue Spruce
    SSG_08_SAND_DUNE = 99, // Sand Dune
    SSG_08_RAPID_TRANSIT = 128, // Rapid Transit
    SSG_08_JUNGLE_DASHED = 147, // Jungle Dashed
    SSG_08_MAYAN_DREAMS = 200, // Mayan Dreams
    SSG_08_BLOOD_IN_THE_WATER = 222, // Blood in the Water
    SSG_08_TROPICAL_STORM = 233, // Tropical Storm
    SSG_08_ACID_FADE = 253, // Acid Fade
    SSG_08_SLASHED = 304, // Slashed
    SSG_08_DETOUR = 319, // Detour
    SSG_08_ABYSS = 361, // Abyss
    SSG_08_BIG_IRON = 503, // Big Iron
    SSG_08_ZENO = 513, // Zeno
    SSG_08_NECROPOS = 538, // Necropos
    SSG_08_GHOST_CRUSADER = 554, // Ghost Crusader
    SSG_08_DRAGONFIRE = 624, // Dragonfire
    SSG_08_DEATHS_HEAD = 670, // Death's Head
    SSG_08_ORANGE_FILIGREE = 743, // Orange Filigree
    SSG_08_HAND_BRAKE = 751, // Hand Brake
    SSG_08_RED_STONE = 762, // Red Stone
    SSG_08_SEA_CALICO = 868, // Sea Calico
    SSG_08_HALFTONE_WHORL = 877, // Halftone Whorl
    SSG_08_BLOODSHOT = 899, // Bloodshot
    SSG_08_PREY = 935, // Prey
    SSG_08_FEVER_DREAM = 956, // Fever Dream
    SSG_08_MAINFRAME_001 = 967, // Mainframe 001
    SSG_08_PARALLAX = 989, // Parallax
    SSG_08_THREAT_DETECTED = 996, // Threat Detected
    SSG_08_DEATH_STRIKE = 1052, // Death Strike
    SSG_08_SPRING_TWILLY = 1060, // Spring Twilly
    SSG_08_TURBO_PEEK = 1101, // Turbo Peek
    SSG_08_DEZASTRE = 1161, // Dezastre
    SSG_08_MEMORIAL = 1187, // Memorial
    SSG_08_AZURE_GLYPH = 1251, // Azure Glyph
    SSG_08_GREY_SMOKE = 1271, // Grey Smoke
    SSG_08_TIGER_TEAR = 1289, // Tiger Tear
    SSG_08_GREEN_CERAMIC = 1304, // Green Ceramic
    SSG_08_BLUSH_POUR = 1316, // Blush Pour

    // Sawed-Off Skins
    SAWED_OFF_FOREST_DDPAT = 5, // Forest DDPAT
    SAWED_OFF_SNAKE_CAMO = 30, // Snake Camo
    SAWED_OFF_COPPER = 41, // Copper
    SAWED_OFF_ORANGE_DDPAT = 83, // Orange DDPAT
    SAWED_OFF_SAGE_SPRAY = 119, // Sage Spray
    SAWED_OFF_IRRADIATED_ALERT = 171, // Irradiated Alert
    SAWED_OFF_MOSAICO = 204, // Mosaico
    SAWED_OFF_AMBER_FADE = 246, // Amber Fade
    SAWED_OFF_FULL_STOP = 250, // Full Stop
    SAWED_OFF_THE_KRAKEN = 256, // The Kraken
    SAWED_OFF_RUST_COAT = 323, // Rust Coat
    SAWED_OFF_FIRST_CLASS = 345, // First Class
    SAWED_OFF_HIGHWAYMAN = 390, // Highwayman
    SAWED_OFF_SERENITY = 405, // Serenity
    SAWED_OFF_ORIGAMI = 434, // Origami
    SAWED_OFF_BAMBOO_SHADOW = 458, // Bamboo Shadow
    SAWED_OFF_YORICK = 517, // Yorick
    SAWED_OFF_FUBAR = 552, // Fubar
    SAWED_OFF_LIMELIGHT = 596, // Limelight
    SAWED_OFF_WASTELAND_PRINCESS = 638, // Wasteland Princess
    SAWED_OFF_ZANDER = 655, // Zander
    SAWED_OFF_MORRIS = 673, // Morris
    SAWED_OFF_DEVOURER = 720, // Devourer
    SAWED_OFF_BRAKE_LIGHT = 797, // Brake Light
    SAWED_OFF_BLACK_SAND = 814, // Black Sand
    SAWED_OFF_JUNGLE_THICKET = 870, // Jungle Thicket
    SAWED_OFF_PARCHED = 880, // Parched
    SAWED_OFF_APOCALYPTO = 953, // Apocalypto
    SAWED_OFF_CLAY_AMBUSH = 1014, // Clay Ambush
    SAWED_OFF_SPIRIT_BOARD = 1140, // Spirit Board
    SAWED_OFF_KISSLOVE = 1155, // Kiss♥Love
    SAWED_OFF_ANALOG_INPUT = 1160, // Analog Input
    SAWED_OFF_RUNOFF = 1272, // Runoff

    // Shadow Daggers Skins
    SHADOW_DAGGERS_FOREST_DDPAT = 5, // Forest DDPAT
    SHADOW_DAGGERS_CRIMSON_WEB = 12, // Crimson Web
    SHADOW_DAGGERS_FADE = 38, // Fade
    SHADOW_DAGGERS_NIGHT = 40, // Night
    SHADOW_DAGGERS_BLUE_STEEL = 42, // Blue Steel
    SHADOW_DAGGERS_STAINED = 43, // Stained
    SHADOW_DAGGERS_CASE_HARDENED = 44, // Case Hardened
    SHADOW_DAGGERS_SLAUGHTER = 59, // Slaughter
    SHADOW_DAGGERS_SAFARI_MESH = 72, // Safari Mesh
    SHADOW_DAGGERS_BOREAL_FOREST = 77, // Boreal Forest
    SHADOW_DAGGERS_ULTRAVIOLET = 98, // Ultraviolet
    SHADOW_DAGGERS_URBAN_MASKED = 143, // Urban Masked
    SHADOW_DAGGERS_SCORCHED = 175, // Scorched
    SHADOW_DAGGERS_TIGER_TOOTH = 409, // Tiger Tooth
    SHADOW_DAGGERS_DAMASCUS_STEEL = 411, // Damascus Steel
    SHADOW_DAGGERS_MARBLE_FADE = 413, // Marble Fade
    SHADOW_DAGGERS_RUST_COAT = 414, // Rust Coat
    SHADOW_DAGGERS_GAMMA_DOPPLER = 568, // Gamma Doppler
    SHADOW_DAGGERS_BRIGHT_WATER = 579, // Bright Water
    SHADOW_DAGGERS_FREEHAND = 581, // Freehand
    SHADOW_DAGGERS_DOPPLER = 617, // Doppler
    SHADOW_DAGGERS_LORE = 1108, // Lore
    SHADOW_DAGGERS_BLACK_LAMINATE = 1113, // Black Laminate
    SHADOW_DAGGERS_AUTOTRONIC = 1118, // Autotronic

    // Skeleton Knife Skins
    SKELETON_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    SKELETON_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    SKELETON_KNIFE_FADE = 38, // Fade
    SKELETON_KNIFE_BLUE_STEEL = 42, // Blue Steel
    SKELETON_KNIFE_STAINED = 43, // Stained
    SKELETON_KNIFE_CASE_HARDENED = 44, // Case Hardened
    SKELETON_KNIFE_SLAUGHTER = 59, // Slaughter
    SKELETON_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    SKELETON_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    SKELETON_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    SKELETON_KNIFE_URBAN_MASKED = 143, // Urban Masked
    SKELETON_KNIFE_SCORCHED = 175, // Scorched
    SKELETON_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    SKELETON_KNIFE_DAMASCUS_STEEL = 410, // Damascus Steel
    SKELETON_KNIFE_MARBLE_FADE = 413, // Marble Fade
    SKELETON_KNIFE_RUST_COAT = 414, // Rust Coat
    SKELETON_KNIFE_DOPPLER = 417, // Doppler
    SKELETON_KNIFE_NIGHT_STRIPE = 735, // Night Stripe

    // Specialist Gloves Skins
    SPECIALIST_GLOVES_FOREST_DDPAT = 10030, // Forest DDPAT
    SPECIALIST_GLOVES_CRIMSON_KIMONO = 10033, // Crimson Kimono
    SPECIALIST_GLOVES_EMERALD_WEB = 10034, // Emerald Web
    SPECIALIST_GLOVES_FOUNDATION = 10035, // Foundation
    SPECIALIST_GLOVES_CRIMSON_WEB = 10061, // Crimson Web
    SPECIALIST_GLOVES_BUCKSHOT = 10062, // Buckshot
    SPECIALIST_GLOVES_FADE = 10063, // Fade
    SPECIALIST_GLOVES_MOGUL = 10064, // Mogul
    SPECIALIST_GLOVES_MARBLE_FADE = 10065, // Marble Fade
    SPECIALIST_GLOVES_LT_COMMANDER = 10066, // Lt. Commander
    SPECIALIST_GLOVES_TIGER_STRIKE = 10067, // Tiger Strike
    SPECIALIST_GLOVES_FIELD_AGENT = 10068, // Field Agent

    // Sport Gloves Skins
    SPORT_GLOVES_SUPERCONDUCTOR = 10018, // Superconductor
    SPORT_GLOVES_ARID = 10019, // Arid
    SPORT_GLOVES_PANDORAS_BOX = 10037, // Pandora's Box
    SPORT_GLOVES_HEDGE_MAZE = 10038, // Hedge Maze
    SPORT_GLOVES_AMPHIBIOUS = 10045, // Amphibious
    SPORT_GLOVES_BRONZE_MORPH = 10046, // Bronze Morph
    SPORT_GLOVES_OMEGA = 10047, // Omega
    SPORT_GLOVES_VICE = 10048, // Vice
    SPORT_GLOVES_SLINGSHOT = 10073, // Slingshot
    SPORT_GLOVES_BIG_GAME = 10074, // Big Game
    SPORT_GLOVES_SCARLET_SHAMAGH = 10075, // Scarlet Shamagh
    SPORT_GLOVES_NOCTS = 10076, // Nocts

    // Stiletto Knife Skins
    STILETTO_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    STILETTO_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    STILETTO_KNIFE_FADE = 38, // Fade
    STILETTO_KNIFE_BLUE_STEEL = 42, // Blue Steel
    STILETTO_KNIFE_STAINED = 43, // Stained
    STILETTO_KNIFE_CASE_HARDENED = 44, // Case Hardened
    STILETTO_KNIFE_SLAUGHTER = 59, // Slaughter
    STILETTO_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    STILETTO_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    STILETTO_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    STILETTO_KNIFE_URBAN_MASKED = 143, // Urban Masked
    STILETTO_KNIFE_SCORCHED = 175, // Scorched
    STILETTO_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    STILETTO_KNIFE_MARBLE_FADE = 413, // Marble Fade
    STILETTO_KNIFE_RUST_COAT = 414, // Rust Coat
    STILETTO_KNIFE_DOPPLER = 417, // Doppler
    STILETTO_KNIFE_NIGHT_STRIPE = 735, // Night Stripe
    STILETTO_KNIFE_DAMASCUS_STEEL = 857, // Damascus Steel

    // Survival Knife Skins
    SURVIVAL_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    SURVIVAL_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    SURVIVAL_KNIFE_FADE = 38, // Fade
    SURVIVAL_KNIFE_BLUE_STEEL = 42, // Blue Steel
    SURVIVAL_KNIFE_STAINED = 43, // Stained
    SURVIVAL_KNIFE_CASE_HARDENED = 44, // Case Hardened
    SURVIVAL_KNIFE_SLAUGHTER = 59, // Slaughter
    SURVIVAL_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    SURVIVAL_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    SURVIVAL_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    SURVIVAL_KNIFE_URBAN_MASKED = 143, // Urban Masked
    SURVIVAL_KNIFE_SCORCHED = 175, // Scorched
    SURVIVAL_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    SURVIVAL_KNIFE_DAMASCUS_STEEL = 410, // Damascus Steel
    SURVIVAL_KNIFE_MARBLE_FADE = 413, // Marble Fade
    SURVIVAL_KNIFE_RUST_COAT = 414, // Rust Coat
    SURVIVAL_KNIFE_DOPPLER = 417, // Doppler
    SURVIVAL_KNIFE_NIGHT_STRIPE = 735, // Night Stripe

    // Talon Knife Skins
    TALON_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    TALON_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    TALON_KNIFE_FADE = 38, // Fade
    TALON_KNIFE_BLUE_STEEL = 42, // Blue Steel
    TALON_KNIFE_STAINED = 43, // Stained
    TALON_KNIFE_CASE_HARDENED = 44, // Case Hardened
    TALON_KNIFE_SLAUGHTER = 59, // Slaughter
    TALON_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    TALON_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    TALON_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    TALON_KNIFE_URBAN_MASKED = 143, // Urban Masked
    TALON_KNIFE_SCORCHED = 175, // Scorched
    TALON_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    TALON_KNIFE_RUST_COAT = 414, // Rust Coat
    TALON_KNIFE_DOPPLER = 417, // Doppler
    TALON_KNIFE_NIGHT_STRIPE = 735, // Night Stripe
    TALON_KNIFE_MARBLE_FADE = 856, // Marble Fade
    TALON_KNIFE_DAMASCUS_STEEL = 858, // Damascus Steel

    // Tec-9 Skins
    TEC_9_GROUNDWATER = 2, // Groundwater
    TEC_9_URBAN_DDPAT = 17, // Urban DDPAT
    TEC_9_OSSIFIED = 36, // Ossified
    TEC_9_BRASS = 159, // Brass
    TEC_9_NUCLEAR_THREAT = 179, // Nuclear Threat
    TEC_9_TORNADO = 206, // Tornado
    TEC_9_BLUE_TITANIUM = 216, // Blue Titanium
    TEC_9_VARICAMO = 235, // VariCamo
    TEC_9_ARMY_MESH = 242, // Army Mesh
    TEC_9_RED_QUARTZ = 248, // Red Quartz
    TEC_9_TITANIUM_BIT = 272, // Titanium Bit
    TEC_9_SANDSTORM = 289, // Sandstorm
    TEC_9_ISAAC = 303, // Isaac
    TEC_9_TOXIC = 374, // Toxic
    TEC_9_HADES = 439, // Hades
    TEC_9_BAMBOO_FOREST = 459, // Bamboo Forest
    TEC_9_TERRACE = 463, // Terrace
    TEC_9_AVALANCHE = 520, // Avalanche
    TEC_9_JAMBIYA = 539, // Jambiya
    TEC_9_RE_ENTRY = 555, // Re-Entry
    TEC_9_ICE_CAP = 599, // Ice Cap
    TEC_9_FUEL_INJECTOR = 614, // Fuel Injector
    TEC_9_CUT_OUT = 671, // Cut Out
    TEC_9_CRACKED_OPAL = 684, // Cracked Opal
    TEC_9_SNEK_9 = 722, // Snek-9
    TEC_9_RUST_LEAF = 733, // Rust Leaf
    TEC_9_ORANGE_MURANO = 738, // Orange Murano
    TEC_9_TIGER_STENCIL = 766, // Tiger Stencil
    TEC_9_REMOTE_CONTROL = 791, // Remote Control
    TEC_9_SAFETY_NET = 795, // Safety Net
    TEC_9_FUBAR = 816, // Fubar
    TEC_9_BAMBOOZLE = 839, // Bamboozle
    TEC_9_DECIMATOR = 889, // Decimator
    TEC_9_FLASH_OUT = 905, // Flash Out
    TEC_9_BROTHER = 964, // Brother
    TEC_9_PHOENIX_CHALK = 1010, // Phoenix Chalk
    TEC_9_BLAST_FROM_THE_PAST = 1024, // Blast From the Past
    TEC_9_SLAG = 1159, // Slag
    TEC_9_WHITEOUT = 1214, // Whiteout
    TEC_9_REBEL = 1235, // Rebel
    TEC_9_MUMMYS_ROT = 1252, // Mummy's Rot
    TEC_9_BLUE_BLAST = 1279, // Blue Blast
    TEC_9_GARTER_9 = 1286, // Garter-9
    TEC_9_RAW_CERAMIC = 1299, // Raw Ceramic
    TEC_9_CITRIC_ACID = 1322, // Citric Acid

    // UMP-45 Skins
    UMP_45_GUNSMOKE = 15, // Gunsmoke
    UMP_45_URBAN_DDPAT = 17, // Urban DDPAT
    UMP_45_BLAZE = 37, // Blaze
    UMP_45_CARBON_FIBER = 70, // Carbon Fiber
    UMP_45_MUDDER = 90, // Mudder
    UMP_45_CARAMEL = 93, // Caramel
    UMP_45_NEO_NOIR = 131, // Neo-Noir
    UMP_45_FALLOUT_WARNING = 169, // Fallout Warning
    UMP_45_SCORCHED = 175, // Scorched
    UMP_45_BONE_PILE = 193, // Bone Pile
    UMP_45_FULL_STOP = 250, // Full Stop
    UMP_45_CORPORAL = 281, // Corporal
    UMP_45_INDIGO = 333, // Indigo
    UMP_45_LABYRINTH = 362, // Labyrinth
    UMP_45_DELUSION = 392, // Delusion
    UMP_45_CRIMSON_FOIL = 412, // Crimson Foil
    UMP_45_GRAND_PRIX = 436, // Grand Prix
    UMP_45_MINOTAURS_LABYRINTH = 441, // Minotaur's Labyrinth
    UMP_45_RIOT = 488, // Riot
    UMP_45_PRIMAL_SABER = 556, // Primal Saber
    UMP_45_BRIEFING = 615, // Briefing
    UMP_45_SCAFFOLD = 652, // Scaffold
    UMP_45_METAL_FLOWERS = 672, // Metal Flowers
    UMP_45_EXPOSURE = 688, // Exposure
    UMP_45_ARCTIC_WOLF = 704, // Arctic Wolf
    UMP_45_DAY_LILY = 725, // Day Lily
    UMP_45_FACILITY_DARK = 778, // Facility Dark
    UMP_45_MOMENTUM = 802, // Momentum
    UMP_45_MOONRISE = 851, // Moonrise
    UMP_45_FADE = 879, // Fade
    UMP_45_PLASTIQUE = 916, // Plastique
    UMP_45_GOLD_BISMUTH = 990, // Gold Bismuth
    UMP_45_CRIME_SCENE = 1003, // Crime Scene
    UMP_45_HOUNDSTOOTH = 1008, // Houndstooth
    UMP_45_OSCILLATOR = 1049, // Oscillator
    UMP_45_MECHANISM = 1085, // Mechanism
    UMP_45_ROADBLOCK = 1157, // Roadblock
    UMP_45_MOTORIZED = 1175, // Motorized
    UMP_45_KO_FACTORY = 1194, // K.O. Factory
    UMP_45_LATE_NIGHT_TRANSIT = 1203, // Late Night Transit
    UMP_45_WILD_CHILD = 1236, // Wild Child
    UMP_45_GREEN_SWIRL = 1303, // Green Swirl

    // USP-S Skins
    USP_S_FOREST_LEAVES = 25, // Forest Leaves
    USP_S_DARK_WATER = 60, // Dark Water
    USP_S_27 = 115, // 27
    USP_S_OVERGROWTH = 183, // Overgrowth
    USP_S_BLOOD_TIGER = 217, // Blood Tiger
    USP_S_SERUM = 221, // Serum
    USP_S_NIGHT_OPS = 236, // Night Ops
    USP_S_STAINLESS = 277, // Stainless
    USP_S_GUARDIAN = 290, // Guardian
    USP_S_ORION = 313, // Orion
    USP_S_ROAD_RASH = 318, // Road Rash
    USP_S_ROYAL_BLUE = 332, // Royal Blue
    USP_S_CAIMAN = 339, // Caiman
    USP_S_BUSINESS_CLASS = 364, // Business Class
    USP_S_PATHFINDER = 443, // Pathfinder
    USP_S_PARA_GREEN = 454, // Para Green
    USP_S_TORQUE = 489, // Torque
    USP_S_KILL_CONFIRMED = 504, // Kill Confirmed
    USP_S_LEAD_CONDUIT = 540, // Lead Conduit
    USP_S_CYREX = 637, // Cyrex
    USP_S_NEO_NOIR = 653, // Neo-Noir
    USP_S_BLUEPRINT = 657, // Blueprint
    USP_S_CORTEX = 705, // Cortex
    USP_S_CHECK_ENGINE = 796, // Check Engine
    USP_S_FLASHBACK = 817, // Flashback
    USP_S_PURPLE_DDPAT = 818, // Purple DDPAT
    USP_S_ALPINE_CAMO = 830, // Alpine Camo
    USP_S_ORANGE_ANOLIS = 922, // Orange Anolis
    USP_S_MONSTER_MASHUP = 991, // Monster Mashup
    USP_S_TARGET_ACQUIRED = 1027, // Target Acquired
    USP_S_ANCIENT_VISIONS = 1031, // Ancient Visions
    USP_S_THE_TRAITOR = 1040, // The Traitor
    USP_S_WHITEOUT = 1065, // Whiteout
    USP_S_BLACK_LOTUS = 1102, // Black Lotus
    USP_S_TICKET_TO_HELL = 1136, // Ticket to Hell
    USP_S_PRINTSTREAM = 1142, // Printstream
    USP_S_JAWBREAKER = 1173, // Jawbreaker
    USP_S_PC_GRN = 1186, // PC-GRN
    USP_S_ROYAL_GUARD = 1217, // Royal Guard
    USP_S_DESERT_TACTICAL = 1253, // Desert Tactical
    USP_S_TROPICAL_BREEZE = 1284, // Tropical Breeze
    USP_S_BLEEDING_EDGE = 1323, // Bleeding Edge

    // Ursus Knife Skins
    URSUS_KNIFE_FOREST_DDPAT = 5, // Forest DDPAT
    URSUS_KNIFE_CRIMSON_WEB = 12, // Crimson Web
    URSUS_KNIFE_FADE = 38, // Fade
    URSUS_KNIFE_BLUE_STEEL = 42, // Blue Steel
    URSUS_KNIFE_STAINED = 43, // Stained
    URSUS_KNIFE_CASE_HARDENED = 44, // Case Hardened
    URSUS_KNIFE_SLAUGHTER = 59, // Slaughter
    URSUS_KNIFE_SAFARI_MESH = 72, // Safari Mesh
    URSUS_KNIFE_BOREAL_FOREST = 77, // Boreal Forest
    URSUS_KNIFE_ULTRAVIOLET = 98, // Ultraviolet
    URSUS_KNIFE_URBAN_MASKED = 143, // Urban Masked
    URSUS_KNIFE_SCORCHED = 175, // Scorched
    URSUS_KNIFE_TIGER_TOOTH = 409, // Tiger Tooth
    URSUS_KNIFE_MARBLE_FADE = 413, // Marble Fade
    URSUS_KNIFE_RUST_COAT = 414, // Rust Coat
    URSUS_KNIFE_DOPPLER = 417, // Doppler
    URSUS_KNIFE_NIGHT_STRIPE = 735, // Night Stripe
    URSUS_KNIFE_DAMASCUS_STEEL = 857, // Damascus Steel

    // XM1014 Skins
    XM1014_BLUE_STEEL = 42, // Blue Steel
    XM1014_GRASSLAND = 95, // Grassland
    XM1014_BLUE_SPRUCE = 96, // Blue Spruce
    XM1014_URBAN_PERFORATED = 135, // Urban Perforated
    XM1014_MONSTER_MELT = 146, // Monster Melt
    XM1014_BLAZE_ORANGE = 166, // Blaze Orange
    XM1014_FALLOUT_WARNING = 169, // Fallout Warning
    XM1014_JUNGLE = 205, // Jungle
    XM1014_VARICAMO_BLUE = 238, // VariCamo Blue
    XM1014_CALICAMO = 240, // CaliCamo
    XM1014_HEAVEN_GUARD = 314, // Heaven Guard
    XM1014_RED_PYTHON = 320, // Red Python
    XM1014_RED_LEATHER = 348, // Red Leather
    XM1014_BONE_MACHINE = 370, // Bone Machine
    XM1014_TRANQUILITY = 393, // Tranquility
    XM1014_QUICKSILVER = 407, // Quicksilver
    XM1014_SCUMBRIA = 505, // Scumbria
    XM1014_TECLU_BURNER = 521, // Teclu Burner
    XM1014_BLACK_TIE = 557, // Black Tie
    XM1014_SLIPSTREAM = 616, // Slipstream
    XM1014_SEASONS = 654, // Seasons
    XM1014_ZIGGY = 689, // Ziggy
    XM1014_OXIDE_BLAZE = 706, // Oxide Blaze
    XM1014_BANANA_LEAF = 731, // Banana Leaf
    XM1014_FROST_BORRE = 760, // Frost Borre
    XM1014_ELEGANT_VINES = 821, // Elegant Vines
    XM1014_HALFTONE_SHIFT = 834, // Halftone Shift
    XM1014_INCINEGATOR = 850, // Incinegator
    XM1014_ENTOMBED = 970, // Entombed
    XM1014_CHARTER = 994, // Charter
    XM1014_ANCIENT_LORE = 1021, // Ancient Lore
    XM1014_XOXO = 1046, // XOXO
    XM1014_BLUE_TIRE = 1078, // Blue Tire
    XM1014_WATCHDOG = 1103, // Watchdog
    XM1014_ZOMBIE_OFFENSIVE = 1135, // Zombie Offensive
    XM1014_IREZUMI = 1174, // Irezumi
    XM1014_MOCKINGBIRD = 1182, // Mockingbird
    XM1014_RUN_RUN_RUN = 1201, // Run Run Run
    XM1014_SOLITUDE = 1215, // Solitude
    XM1014_HIEROGLYPH = 1254, // Hieroglyph
    XM1014_GUM_WALL_CAMO = 1267, // Gum Wall Camo
    XM1014_COPPERFLAGE = 1287, // Copperflage
    XM1014_CANVAS_CLOUD = 1333, // Canvas Cloud

    // Zeus x27 Skins
    ZEUS_X27_DRAGON_SNORE = 292, // Dragon Snore
    ZEUS_X27_OLYMPUS = 1172, // Olympus
    ZEUS_X27_TOSAI = 1183, // Tosai
    ZEUS_X27_CHARGED_UP = 1205, // Charged Up
    ZEUS_X27_ELECTRIC_BLUE = 1268, // Electric Blue
    ZEUS_X27_SWAMP_DDPAT = 1297, // Swamp DDPAT

}

/**
 * Type guard to check if a value is a valid WeaponPaint
 */
export function isWeaponPaint(value: any): value is WeaponPaint {
    return typeof value === 'number' && Object.values(WeaponPaint).includes(value);
}

/**
 * Get paint name from paint index
 */
export function getPaintName(paintIndex: number): string | undefined {
    const paintEntry = Object.entries(WeaponPaint).find(([, value]) => value === paintIndex);
    return paintEntry ? paintEntry[0] : undefined;
}

/**
 * Get paint index from paint name
 */
export function getPaintIndex(paintName: string): number | undefined {
    const upperName = paintName.toUpperCase();
    return WeaponPaint[upperName as keyof typeof WeaponPaint];
}

/**
 * Get all available paint names
 */
export function getAllPaintNames(): string[] {
    return Object.keys(WeaponPaint).filter(key => isNaN(Number(key)));
}

/**
 * Get all available paint indices
 */
export function getAllPaintIndices(): number[] {
    return Object.values(WeaponPaint).filter(value => typeof value === 'number') as number[];
}

/**
 * Search for paints by weapon name
 */
export function getPaintsByWeapon(weaponName: string): Array<{key: string, index: number}> {
    const upperWeapon = weaponName.toUpperCase().replace(/[^A-Z0-9]/g, '_');
    const results: Array<{key: string, index: number}> = [];
    
    Object.entries(WeaponPaint).forEach(([key, value]) => {
        if (typeof value === 'number' && key.startsWith(upperWeapon)) {
            results.push({ key, index: value });
        }
    });
    
    return results.sort((a, b) => a.index - b.index);
}

/**
 * Search for paints by pattern name
 */
export function getPaintsByPattern(patternName: string): Array<{key: string, index: number}> {
    const upperPattern = patternName.toUpperCase().replace(/[^A-Z0-9]/g, '_');
    const results: Array<{key: string, index: number}> = [];
    
    Object.entries(WeaponPaint).forEach(([key, value]) => {
        if (typeof value === 'number' && key.includes(upperPattern)) {
            results.push({ key, index: value });
        }
    });
    
    return results.sort((a, b) => a.index - b.index);
}
